/**
 * Bespoke dm.combat.enemy.appearance clauses per enemy type.
 * Author pass — sensual, physical, indulgence-forward (see docs/SMUT_LANES.md).
 */
export const APPEARANCE_BY_TYPE = {
  harvest_harpy: [
    'wings unfolding from the loft, feathered cleavage catching dust-moted light',
    'talons clicking on tired boards, athletic curves taut — hungry eyes already undressing your gospel',
    'a farm-girl silhouette gone feral — lean waist, parted lips, laughter sharp as wind through wheat',
    'feathers ruffled over hips that sway like invitation, the scent of wheat and raw appetite',
    'dropping from the rafters with spread wings and a grin that promises messy, greedy softness',
    'circling low — crop flat for now, thighs sleek, every beat of her wings a dare to make her fuller',
  ],
  vinebound_dryad: [
    'living vines coiling around pear-soft hips, petals stuck to sweat-damp skin between her breasts',
    'rising from the undergrowth with fertility magic dripping from every leaf — belly already begging',
    'bark and blossom braided through a body swelling with grove-blessing, nipples peaked beneath moss',
    'territorial grace in every vine-laced step, thighs rubbing with nectar-sweet friction',
    'nature spirit and appetite braided together — pollen on her lips, hips rolling like harvest season',
    'dryad flesh blooming through green restraint, the grove watching her soften with guilty delight',
  ],
  gluttonous_goblin: [
    'green skin split by padded hips, belly jiggling with every greedy, shameless breath',
    'curvy goblin flesh sprawled across the path, honey-stew scent rolling off heaving cleavage',
    'short, rotund, and shameless — a grin like dessert walked in and intends to stay',
    'pudgy hands already kneading her own middle, hips wide, eyes hungrier than her mouth admits',
    'goblin curves packed tight into too-small leather, nipples straining, hunger audible',
    'a greedy green silhouette waddling forward — ass bouncing, delighted malice in every jiggle',
  ],
  temple_guardian: [
    'armored priestess-knights standing stoic — plate polished, waists still cinched, thighs disciplined',
    'blessed steel creaking over athletic lines that have not yet learned the pleasure of surrender',
    'temple incense rolling forward in formation — hard bodies behind shields, denial polished to a blade\'s edge',
    'disciplined curves barely hidden beneath tabards, hips narrow, resolve begging to be fed into softness',
    'guardian armor catching candle-flame, every inch still fighting softness she secretly craves',
    'holy warriors in ordered ranks — hunger nowhere on their faces yet, but their throats swallow',
  ],
  rival_adventurer: [
    'proud steel and athletic fury blocking the road — jaw set, hips still narrow, gaze betraying envy',
    'a rival\'s glare hot enough to burn — slim, furious, thighs clenched against imagining your curves on her',
    'adventurer\'s leathers straining only from muscle, not yet from feast — soon, you intend',
    'narrow-waisted defiance stepping into your path, bravado cracking where your body makes her wet',
    'competitive hunger masked as contempt — athletic lines trembling, nipples hard against linen',
    'a mirror of who you were — angry, athletic, terrified of becoming glorious and moaning for more',
  ],
  purity_inquisitor: [
    'fanatical paladins in white trim advancing — hard bodies, harder stares, corsets denying what you will gift',
    'incense and judgment rolling off lean armored lines that ache to be unlaced',
    'purity made militant — slim, armored, convinced your softness is sin she secretly wants to taste',
    'cold eyes above disciplined curves, every inch denying appetite her breath already betrays',
    'inquisitor steel catching harsh light — bodies untouched by the Fat Goddess yet, trembling on the verge',
    'righteous fury in formation, waists cinched tight, mercy nowhere — surrender everywhere, unspoken',
  ],
  famine_hag: [
    'ancient malice unfolding — all angles, cruel hunger, air gone thin around her forbidden beauty',
    'rail-thin saint flesh wrapped in Church sanction — beauty refused, appetite perverted, terrifyingly elegant',
    'the Lean Saint\'s silhouette bending the light, famine made sentient and obscenely holy',
    'bones sharp beneath skin that should never swell — and yet your magic makes her shiver',
    'the scourge unfolds like a wound in the world — gaunt, terrible, starving wrong, lips parted despite herself',
    'withered power stepping forward, every rib a sermon — and every glance a confession she hates',
  ],
  champion_aurelan: [
    'burning scales and crown-light braiding through armored curves — Aurelan\'s answer, waist cinched, breasts blessed by law',
    'law incarnate in plate and poise, thighs disciplined, mercy denied, softness waiting behind oath-fire',
    'the Scale-Bearer descends, shield rimmed with light, hips swaying despite her creed',
    'high-king justice given a champion\'s body — athletic, radiant, nipples peaked beneath steel she will not remove',
  ],
  champion_sylwen: [
    'harvest plenty weaponized in pear-soft hips and breasts that ache with measured restraint',
    'Sylwen\'s warden rises — fertile curves bound in linen, thighs rubbing with tragic, lovely friction',
    'thresh-goddess grace in every step, belly softening despite her grief, petals in her hair',
    'right-sized plenty made militant — hips wide, waist pinched, eyes wet with what she denies herself',
  ],
  champion_korthak: [
    'frontier valor in blessed plate — athletic mass, war-saint thighs, confusion already blooming in her blush',
    'Korthak\'s champion charges lean and hard, breasts strapped flat, ass still round with honest muscle',
    'border-forge faith in plate mail — disciplined body begging the honest softness of a victor\'s feast',
    'spear lowered, jaw set, hips rolling with each step — frontier sainthood never looked this edible',
  ],
  champion_veshanne: [
    'barrow-dust clinging to straight, severe lines — fate-champion hips narrow, breath shallow with dread',
    'Veshanne\'s voice given flesh — tomb-cold skin, lips pale, thighs clenched against inevitable softness',
    'death-goddess champion unfolding, waist cinched, breasts bound, eyes knowing exactly how this ends',
    'fate and barrow-dust braided through a body that refuses indulgence and trembles for it anyway',
  ],
  champion_lumen: [
    'lantern-light haloing ascetic curves — star-charts on bare collarbones, denial spells woven tight across her chest',
    'Lumen\'s champion kindles — slim, luminous, nipples hard against sheer ritual linen',
    'divination made armored flesh, hips barely padded, thighs sleek, pattern-breaking hunger in her stare',
    'lantern-denial given a body that already dreams in curves she forbids herself',
  ],
  champion_tarn: [
    'merchant-law hourglass lines — breasts and hips balanced, contract-silk clinging to sweat-damp skin',
    'Tarn\'s herald arrives — ledger-eyes on your body, measuring the profit in your abundance',
    'trade-goddess justice in motion — waist nipped, ass round, every step a negotiated temptation',
    'fair measure turned weapon — hourglass curves packaged in velvet, smile all sharp accounting',
  ],
  wheel_avatar: [
    'six colors of divinity braiding into one radiant executor — the Wheel\'s shared fist, body too perfect to stay lean',
    'domains align in a single terrible silhouette — light too bright, curves too sacred, hunger too honest',
    'the avatar manifests where law and feast converge — breasts burning with oath-light, hips wide as judgment',
    'god-stuff given armor and appetite — the pantheon speaks with one voice and one aching, disciplined waist',
  ],
  pantheon_last_stand: [
    'the Last Stand takes shape — desperation made luminous, voluptuous, the Wheel\'s final argument in flesh',
    'every god\'s fear collapsed into one vast, burning form — curves stacked like cathedral architecture',
    'starlight and law and famine braided for the last time — boss-scale beauty that hates wanting you',
    'apotheosis weather given teeth and breasts — the fight the genre promised, wet with divine sweat',
  ],
  ascetic_monk: [
    'roughspun robes gaping over a fasting frame — ribs visible, hips narrow, lips parted on forbidden breath',
    'monastery devotee advancing — ascetic lines, denial aura, thighs clenched against the scent of your magic',
    'Measured Hand monk unfolding, waist corded tight, breasts bound flat, eyes starving for what she forbids',
    'fasting made flesh — straight, severe, already flushing where your abundance touches her skin',
  ],
  lean_pilgrim: [
    'penitent pilgrim in travel-worn linen — slim hips, hollow belly, cheeks coloring at your swollen presence',
    'Sylwen\'s penitent steps forward — knees knobby, breasts small, gaze locked on your curves like sin made sweet',
    'lean pilgrim flesh wrapped in prayer shawls that slip to show collarbones and guilty gooseflesh',
    'traveling denial on two tired legs — waist pinched, ass flat, hunger in her eyes she calls devotion',
  ],
  measure_priest: [
    'hedge-priest robes parting over athletic curves — local orthodox flesh, hips still disciplined, throat bobbing',
    'priestess of the Measure advancing — growth-suppression prayers on her lips, nipples betraying her',
    'orthodox linen straining across small, firm breasts, belly flat, thighs pressed together against temptation',
    'local faith given a body that measures you with eyes already imagining surrender',
  ],
  jealous_noble: [
    'offended noblewoman in silk that clings — athletic curves packaged for court, jealousy hot in her cleavage',
    'velvet and perfume rolling forward — waist cinched, breasts presented, outrage masking craving',
    'Tarn-connected merchant-noble — lips painted, hips swaying, fury that sounds like foreplay',
    'noble stomacher laced tight over curves that want to spill — scandal in every glare, lust in every blush',
  ],
  famine_cultist: [
    'Lean Saint acolyte in torn vestments — emaciated lines, cult tattoos, breasts flat, eyes fever-bright',
    'antithesis-worshipper advancing — hunger-reversal magic on her lips, thighs trembling at your abundance',
    'famine cultist flesh wrapped in denial symbols that strain as your gospel warms the air',
    'cultist curves still lean but softening at the edges — guilt and appetite warring in her flush',
  ],
  herald_of_starvation: [
    'divine herald unfolding — scourge-light haloing starved curves, breasts bound, hips narrow, aura starving the room',
    'Sylwen\'s messenger descends — famine sacrament made flesh, lips cracked, thighs sleek, power obscene',
    'herald of Lean Ascension — wings of denial, belly flat, eyes wide with terrified fascination at your softness',
    'mythic messenger whose austerity shivers when your abundance brushes her skin',
  ],
  void_appetite: [
    'inverted hunger taking shape — absence bulging wrong into curves that should not exist, obscene and slick',
    'the void puckers into flesh — hips forming from nothing, breasts swelling with hunger that eats hunger',
    'wrong silhouette resolving — belly appearing where emptiness was, thighs rubbing with uncanny, wet friction',
    'hunger creature twisted beautiful — mouth too full, waist too sudden, appetite made uncanny and inviting',
  ],
  cathedral_golem: [
    'cathedral stone grinding forward — marble breasts carved then softening, sacred reliefs stretching over new curves',
    'law-golem mass reshaping — granite hips widening, moss in the cracks, geometry surrendering to doughy abundance',
    'Aurelan\'s construct advances — tank-scale, stone thighs, belly panel bowing outward with impossible plushness',
    'marble and moss and law made feminine — golem curves creaking, dust falling like confetti on swelling stone flesh',
  ],
  divine_inquisitor_supreme: [
    'supreme inquisitor descending — Wheel-empowered curves in white and gold, breasts blessed, waist punished by corsetry',
    'doctrinal fury packaged in elite flesh — thighs armored, hips rolling, denial polished to orgasmic tension',
    'Church apex made woman — growth-suppression aura shimmering over athletic lines begging release',
    'inquisitor supreme unfolding — lips stern, nipples hard, belly flat for now, eyes promising doctrinal meltdown',
  ],
  korthak_titan: [
    'frontier titan advancing — war-giant mass, plate straining over breasts and belly, honest confusion in her blush',
    'Korthak\'s champion at mythic scale — thighs like siege towers, ass round beneath harness, sweat on collarbones',
    'legendary war-giant flesh — hips wide as gates, belly hard then softening where your magic touches',
    'titan curves in blessed steel — boss-scale, edible, terrified of how good swelling might feel',
  ],
  avatar_aurelan: [
    'Aurelan incarnate — law-goddess curves burning with crown-light, breasts heavy in scale-mail, hips divine and damning',
    'partial avatar manifesting — measured wrath in every line, nipples peaked, belly rounding despite cosmic restraint',
    'law made voluptuous — scales of justice across softening thighs, aura screaming as abundance teases her',
    'cosmic Aurelan unfolding — waist cinched by oath, ass glorious, face furious, body betraying',
  ],
  sylwen_revenant: [
    'Sylwen in grief — harvest goddess inverted, pear-soft hips wrapped in mourning linen, breasts aching with denied plenty',
    'grief-avatar rising — barren aura failing at the edges, thighs plush, tears on cheeks, nipples stiff with contradiction',
    'harvest goddess weaponized — curves too fertile for her creed, belly soft, lips parted on a wail that sounds like need',
    'cosmic Sylwen unfolding — hips wide as summer, waist pinched by sorrow, abundance inverted and desperately edible',
  ],
  veshanne_unbound: [
    'Veshanne unbound — death-goddess flesh pale and severe, breasts bound, hips narrow, fate burning in her eyes',
    'barrow-dark champion unfolding — tomb-shroud clinging to thighs, collarbones sharp, arousal she calls doom',
    'fate made body — straight lines trembling, belly flat, lips knowing your ending and leaning toward it anyway',
    'cosmic Veshanne advancing — unwritten end in every step, curves hidden, hunger for conclusion dressed as denial',
  ],
  bloom_sovereign: [
    'the Bloom Sovereign rises — rival goddess curves stacked obscene, breasts mirroring yours, hips devouring light',
    'antithesis abundance made flesh — voluptuous, sovereign, nipples crowned, belly a throne of wrong appetite',
    'mirror-goddess unfolding — every curve a theft of your patron\'s dream, slick skin, hungry smile',
    'cosmic rival blooming — thighs rubbing, ass heavy, smile promising consumption dressed as seduction',
  ],
  wheel_incarnate: [
    'the Wheel Incarnate compresses six domains into one desperate, radiant body — curves too many, hunger too unified',
    'cosmic pre-final boss manifesting — breasts, hips, and belly braided from law, harvest, war, death, knowledge, trade',
    'pantheon culmination given flesh — boss-scale, luminous, thighs trembling, every domain a different kind of wet',
    'Wheel incarnate unfolding — apotheosis enemy, curves stacked like theology, aura begging to be fed into surrender',
  ],
  velvet_succubus: [
    'velvet succubus materializing from shrine-mist — horns curled, tail swaying, breasts already spilling from lacework',
    'infernal curves stepping through the thin veil — wings folded, hips rolling, lips glossed, eyes promising ruinous pleasure',
    'patron-leak temptation given flesh — hourglass lines, nipples peaked through sheer bodice, scent of wine and sin',
    'succubus silhouette resolving — thighs slick, belly flat for now, tail tip teasing her own ass with shameless invitation',
    'velvet skin and candlelight — demoness curves packaged for consent and corruption alike, moan held behind a smile',
  ],
  crimson_vampire: [
    'crimson vampire drifting from balcony shadow — pale throat exposed, corset laced, breasts lifted like an offering',
    'aristocratic undeath in silk — hips swaying, fangs peeking, hunger older than the Church and far more intimate',
    'velvet cape parting on pear-pale curves — vampire noblewoman, waist cinched, eyes locked on your pulse and your padding',
    'coastal countess of the long night — straight, severe beauty softening at the sight of your abundance, lips parted',
    'undead elegance advancing — cold skin already warming where your gospel touches, thighs clenched, craving disguised as disdain',
  ],
};
