export const PLAYER_CLASSES = [
  {
    id: "bard",
    name: "Bard",
    defaultSubclassId: "feast_singer",
    casterType: "half",
    primaryStat: "cha",
    hitDie: 8,
    desc: "Weave songs of abundance. Your performances swell allies and charm enemies into surrender.",
    stats: { str: 10, dex: 14, con: 12, int: 10, wis: 10, cha: 16 },
    proficientSaves: ["dex", "cha"],
    startLbs: 130,
    color: "#d4a017",
  },
  {
    id: "wizard",
    name: "Wizard",
    defaultSubclassId: "school_overflow",
    casterType: "full",
    primaryStat: "int",
    hitDie: 6,
    desc: "Master arcane caloric manipulation. Transmute magic into irresistible growth.",
    stats: { str: 8, dex: 10, con: 10, int: 16, wis: 12, cha: 10 },
    proficientSaves: ["int", "wis"],
    startLbs: 125,
    color: "#6b4fc7",
  },
  {
    id: "cleric",
    name: "Cleric",
    defaultSubclassId: "domain_plenty",
    casterType: "full",
    primaryStat: "wis",
    hitDie: 8,
    desc: "Channel the Fat Goddess's divine abundance. Bless, heal, and swell the faithful.",
    stats: { str: 12, dex: 10, con: 14, int: 10, wis: 16, cha: 12 },
    proficientSaves: ["wis", "cha"],
    startLbs: 135,
    color: "#c9a227",
  },
  {
    id: "warlock",
    name: "Warlock",
    defaultSubclassId: "pact_everfull",
    casterType: "pact",
    primaryStat: "cha",
    hitDie: 8,
    desc: "Draw power from the Fat Goddess's hunger. Drain essence and fuel explosive growth.",
    stats: { str: 10, dex: 12, con: 12, int: 12, wis: 10, cha: 16 },
    proficientSaves: ["wis", "cha"],
    startLbs: 128,
    color: "#8b2252",
  },
];

export function getClass(id) {
  return PLAYER_CLASSES.find((c) => c.id === id) || PLAYER_CLASSES[0];
}
