import { MAX_STAGE_ID } from "./stages.js";

export const COMPANIONS = [
  {
    id: "mira",
    numericId: 0,
    name: "Mira Silverstring",
    class: "Bard",
    subclass: "Feast-Singer",
    bodyType: "hourglass",
    archetype: "performer",
    personality: "Playful, flirtatious wandering musician",
    startLbs: 128,
    recruited: false,
    location: "harvest_hearth",
    ability: "Song of Abundance — performances grant party-wide growth",
  },
  {
    id: "lira",
    numericId: 1,
    name: "Lira Dawnwell",
    class: "Cleric",
    subclass: "Domain of Plenty",
    bodyType: "pear",
    archetype: "devout",
    personality: "Gentle, devout, kind-hearted priestess",
    startLbs: 132,
    recruited: false,
    location: "fertile_heartlands",
    ability: "Divine Aura — passively spreads weight gain nearby",
  },
  {
    id: "sylvie",
    numericId: 2,
    name: 'Sylvara "Sylvie" Thorne',
    class: "Wizard",
    subclass: "School of Overflow",
    bodyType: "apple",
    archetype: "scholar",
    personality: "Curious, nerdy, secretly gluttonous scholar",
    startLbs: 126,
    recruited: false,
    location: "ancient_temple",
    ability: "Arcane Analysis — predict growth and exploit weak points",
  },
  {
    id: "thalia",
    numericId: 3,
    name: "Thalia Blackfeast",
    class: "Warlock",
    subclass: "Pact of the Fat Goddess",
    bodyType: "voluptuous",
    archetype: "dominant",
    personality: "Mysterious, dominant, hedonistic witch",
    startLbs: 140,
    recruited: false,
    location: "gorgara_cradle",
    ability: "Hunger Pact — drain abundance for massive growth",
  },
  {
    id: "greta",
    numericId: 4,
    name: "Greta Ironpot",
    class: "Fighter",
    subclass: "Feast Champion",
    bodyType: "athletic",
    archetype: "competitive",
    personality: "Boisterous, competitive blacksmith",
    startLbs: 155,
    recruited: false,
    location: "harvest_hearth",
    ability: "Iron Belly — consume hazards for healing and growth",
  },
  {
    id: "elara",
    numericId: 5,
    name: "Elara Warmbelly",
    class: "Paladin",
    subclass: "Matron of Plenty",
    bodyType: "rotund",
    archetype: "nurturing",
    personality: "Motherly, nurturing innkeeper",
    startLbs: 148,
    recruited: true,
    location: "harvest_hearth",
    ability: "Feast Matron — creates healing feast camps in combat",
  },
];

export function createCompanionData(template) {
  return {
    ...template,
    lbs: template.startLbs,
    corruption: template.recruited ? 20 : 0,
    relationship: template.recruited ? 40 : 0,
    hp: 30,
    maxHp: 30,
    mp: 15,
    maxMp: 15,
    hunger: 0,
    gender: "she",
    pronouns: "she",
    isCompanion: true,
    sizeCap: MAX_STAGE_ID,
  };
}

export function getCompanion(id) {
  const t = COMPANIONS.find((c) => c.id === id);
  return t ? createCompanionData(t) : null;
}
