import { QUEST_TYPE, QUEST_TAG, OBJECTIVE_TYPE, QUEST_APPROACH, QUEST_SCORE } from '../constants.js';

/**
 * Main quests — world-shaping abundance arcs.
 */
export const MAIN_QUESTS = [
  {
    id: 'main_first_feast_gorgara',
    type: QUEST_TYPE.MAIN,
    act: 1,
    actLabel: 'Act I',
    title: 'The First Feast of the Fat Goddess',
    titleKey: 'quest.main.first_feast.title',
    descriptionKey: 'quest.main.first_feast.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH, QUEST_TAG.CONVERSION],
    region: 'harvest_hearth',
    giverNpcId: 'elara_inn',

    prerequisites: {
      minPlayerLevel: 1,
      questsCompleted: [],
      flags: [],
    },

    stages: [
      {
        id: 'stirring_hunger',
        title: 'Stirring Hunger',
        descriptionKey: 'quest.main.first_feast.stage.stirring.desc',
        approaches: [QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'hear_elara',
            label: 'Speak with Elara about the town\'s stagnation',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'elara_inn',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'survey_hearth',
            label: 'Walk the streets of Harvest\'s Hearth',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'harvest_hearth',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 10, xp: 40 },
          flags: { hearth_stirring: true },
          textKey: 'quest.main.first_feast.stage.stirring.complete',
        },
      },
      {
        id: 'circle_of_influence',
        title: 'Circle of Influence',
        descriptionKey: 'quest.main.first_feast.stage.circle.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.FEEDING, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'befriend_elara',
            label: 'Befriend Elara Warmbelly',
            type: OBJECTIVE_TYPE.NPC_RELATIONSHIP_MIN,
            npcId: 'elara_inn',
            tier: 2,
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'befriend_grikka',
            label: 'Win Grikka\'s feast-queen trust',
            type: OBJECTIVE_TYPE.NPC_RELATIONSHIP_MIN,
            npcId: 'goblin_queen',
            tier: 2,
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 1 },
          },
          {
            id: 'befriend_sylvie',
            label: 'Befriend Sylvie the baker',
            type: OBJECTIVE_TYPE.NPC_RELATIONSHIP_MIN,
            npcId: 'baker_sylvie',
            tier: 2,
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 80 },
          flags: { hearth_influence_won: true },
          textKey: 'quest.main.first_feast.stage.circle.complete',
        },
      },
      {
        id: 'communal_abundance',
        title: 'Communal Abundance',
        descriptionKey: 'quest.main.first_feast.stage.feast.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'host_communal_feast',
            label: 'Host a communal feast in the settlement',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'harvest_hearth',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
          {
            id: 'spread_growth',
            label: 'Help townsfolk swell (4 NPCs gain 2+ size stages)',
            type: OBJECTIVE_TYPE.NPC_GROWTH_QUOTA,
            npcCount: 4,
            minStagesGained: 2,
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 25, xp: 120 },
          flags: { communal_feast_held: true },
          textKey: 'quest.main.first_feast.stage.feast.complete',
        },
      },
      {
        id: 'soften_the_crown',
        title: 'Soften the Crown',
        descriptionKey: 'quest.main.first_feast.stage.crown.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH, QUEST_APPROACH.FEEDING],
        objectives: [
          {
            id: 'crack_vesperia',
            label: 'Break Lady Vesperia\'s resistance',
            type: OBJECTIVE_TYPE.NPC_CORRUPTION_MIN,
            npcId: 'vesperia',
            tier: 2,
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2 },
          },
          {
            id: 'feed_vesperia',
            label: 'Feed Vesperia until poise melts',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'vesperia',
            count: 2,
            growth: { target: 'npc', npcId: 'vesperia', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.DOMINANCE]: 1 },
          },
          {
            id: 'vesperia_transformed',
            label: 'Guide Vesperia to chubby softness',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'vesperia',
            stage: 3,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 20 },
          textKey: 'quest.main.first_feast.stage.crown.complete',
        },
      },
    ],

    endings: [
      {
        id: 'abundant_hearth',
        label: 'Aura of Plenty',
        condition: { minScores: { [QUEST_SCORE.ABUNDANCE]: 6 } },
        rewards: {
          ap: 50,
          xp: 500,
          xpSource: 'major_story',
          playerSizeCapBonus: 1,
          unlockRegions: ['gorgara_cradle'],
          worldAura: { regionId: 'harvest_hearth', name: 'Aura of Plenty', apBonus: 2 },
          worldFlags: { aura_of_plenty_harvest_hearth: true, main_act1_complete: true },
          playerFlags: { first_feast_abundant: true },
          unlockCompanionIds: ['greta'],
        },
        textKey: 'quest.main.first_feast.ending.abundant',
      },
      {
        id: 'converted_hearth',
        label: 'Converted Authority',
        condition: { minScores: { [QUEST_SCORE.CONVERSION]: 3 } },
        rewards: {
          ap: 40,
          xp: 450,
          xpSource: 'major_story',
          unlockRegions: ['gorgara_cradle'],
          worldFlags: { main_act1_complete: true },
          playerFlags: { first_feast_converted: true },
        },
        textKey: 'quest.main.first_feast.ending.converted',
      },
    ],

    rewards: {
      ap: 30,
      xp: 400,
      xpSource: 'major_story',
      worldFlags: { main_act1_complete: true },
      textKey: 'quest.main.first_feast.complete.default',
    },
  },

  {
    id: 'main_overflowing_temple',
    type: QUEST_TYPE.MAIN,
    act: 2,
    actLabel: 'Act II',
    title: 'The Overflowing Temple',
    titleKey: 'quest.main.overflowing_temple.title',
    descriptionKey: 'quest.main.overflowing_temple.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH, QUEST_TAG.CONVERSION],
    region: 'fertile_heartlands',
    giverNpcId: 'harvest_priestess',

    prerequisites: {
      minPlayerLevel: 3,
      flags: ['main_act1_complete'],
      questsCompleted: [],
    },

    stages: [
      {
        id: 'temple_approach',
        title: 'Temple Approach',
        descriptionKey: 'quest.main.overflowing_temple.stage.approach.desc',
        approaches: [QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'counsel_maribel',
            label: 'Learn of the temple\'s resistance from Sister Maribel',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'harvest_priestess',
            count: 2,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'reach_temple',
            label: 'Reach the Ancient Temple ruins',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'ancient_temple',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 12, xp: 60 },
          textKey: 'quest.main.overflowing_temple.stage.approach.complete',
        },
      },
      {
        id: 'inner_circle',
        title: 'Inner Circle',
        descriptionKey: 'quest.main.overflowing_temple.stage.circle.desc',
        approaches: [QUEST_APPROACH.GROWTH, QUEST_APPROACH.FEEDING, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'convert_maribel',
            label: 'Bless Sister Maribel through a major ritual',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'bless',
            npcId: 'harvest_priestess',
            interactionMeta: { blessType: 'major' },
            count: 1,
            growth: { target: 'npc', npcId: 'harvest_priestess', stages: 2, proseKey: 'growth.target.blessing' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.MERCY]: 1 },
          },
          {
            id: 'convert_ash',
            label: 'Nurture Rootmother Ash toward indulgence',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'dryad_elder',
            count: 2,
            growth: { target: 'npc', npcId: 'dryad_elder', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.MERCY]: 1 },
          },
          {
            id: 'priestess_circle',
            label: 'Win Maribel\'s devoted trust',
            type: OBJECTIVE_TYPE.NPC_RELATIONSHIP_MIN,
            npcId: 'harvest_priestess',
            tier: 4,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 100 },
          flags: { temple_circle_converted: true },
          textKey: 'quest.main.overflowing_temple.stage.circle.complete',
        },
      },
      {
        id: 'blooming_ritual',
        title: 'Blooming Ritual',
        descriptionKey: 'quest.main.overflowing_temple.stage.ritual.desc',
        approaches: [QUEST_APPROACH.GROWTH, QUEST_APPROACH.FEEDING],
        objectives: [
          {
            id: 'temple_feast',
            label: 'Hold a feast within the temple halls',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'ancient_temple',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
          {
            id: 'maribel_blooms',
            label: 'Help Maribel reach plump abundance',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'harvest_priestess',
            stage: 4,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 25, xp: 150 },
          worldFlags: { temple_bloomed: true },
          textKey: 'quest.main.overflowing_temple.stage.ritual.complete',
        },
      },
      {
        id: 'ascetic_stand',
        title: 'Ascetic Stand',
        descriptionKey: 'quest.main.overflowing_temple.stage.warriors.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'defeat_guardians',
            label: 'Overcome or convert temple guardians',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'temple_guardian',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 2 },
          },
          {
            id: 'convert_inquisitor',
            label: 'Win a battle against purity inquisitors (any outcome)',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'purity_inquisitor',
            count: 1,
            optional: true,
            score: { [QUEST_SCORE.CONVERSION]: 2, [QUEST_SCORE.MERCY]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 20 },
          textKey: 'quest.main.overflowing_temple.stage.warriors.complete',
        },
      },
    ],

    endings: [
      {
        id: 'sanctuary_of_indulgence',
        label: 'Sanctuary of Indulgence',
        condition: { minScores: { [QUEST_SCORE.MERCY]: 2 } },
        rewards: {
          ap: 55,
          xp: 550,
          xpSource: 'major_story',
          unlockRegions: ['ancient_temple', 'gorgara_cradle'],
          worldFlags: { temple_sanctuary_mercy: true, main_act2_complete: true },
          playerFlags: { cleric_plenty_unlocked: true, warlock_overflow_unlocked: true },
        },
        textKey: 'quest.main.overflowing_temple.ending.mercy',
      },
      {
        id: 'dominion_of_feast',
        label: 'Dominion of the Feast',
        condition: { minScores: { [QUEST_SCORE.DOMINANCE]: 2 } },
        rewards: {
          ap: 50,
          xp: 520,
          xpSource: 'major_story',
          worldFlags: { temple_sanctuary_dominance: true, main_act2_complete: true },
          playerFlags: { cleric_plenty_unlocked: true, warlock_overflow_unlocked: true },
        },
        textKey: 'quest.main.overflowing_temple.ending.dominance',
      },
    ],

    rewards: {
      ap: 35,
      xp: 450,
      xpSource: 'major_story',
      unlockRegions: ['ancient_temple'],
      worldFlags: { main_act2_complete: true },
      playerFlags: { cleric_plenty_unlocked: true, warlock_overflow_unlocked: true },
      textKey: 'quest.main.overflowing_temple.complete.default',
    },
  },

  {
    id: 'main_leviathan_coronation',
    type: QUEST_TYPE.MAIN,
    act: 3,
    actLabel: 'Act III',
    title: "Coronation of Abundance",
    titleKey: 'quest.main.coronation.title',
    descriptionKey: 'quest.main.coronation.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH, QUEST_TAG.CONVERSION],
    region: 'gorgara_cradle',
    giverNpcId: 'thalia_witch',

    prerequisites: {
      minPlayerLevel: 8,
      questsCompleted: ['main_overflowing_temple'],
      flags: ['main_act2_complete'],
    },

    stages: [
      {
        id: 'cradle_hunger',
        title: 'Hunger at the Cradle',
        descriptionKey: 'quest.main.coronation.stage.cradle.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'meet_thalia',
            label: 'Seek Thalia at Shrine of the Thin Veil',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'gorgara_cradle',
            count: 1,
          },
          {
            id: 'thalia_close',
            label: 'Earn Thalia\'s intimate trust',
            type: OBJECTIVE_TYPE.NPC_RELATIONSHIP_MIN,
            npcId: 'thalia',
            tier: 3,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 80 },
          textKey: 'quest.main.coronation.stage.cradle.complete',
        },
      },
      {
        id: 'spread_overflow',
        title: 'Spread the Overflow',
        descriptionKey: 'quest.main.coronation.stage.spread.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'growth_quota_cradle',
            label: 'Guide three souls to significant growth in the cradle',
            type: OBJECTIVE_TYPE.NPC_GROWTH_QUOTA,
            regionId: 'gorgara_cradle',
            minStagesGained: 2,
            count: 3,
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
          {
            id: 'feast_ritual',
            label: 'Host a communal feast',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'gorgara_cradle',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 30, xp: 120, playerSizeCapBonus: 1 },
          textKey: 'quest.main.coronation.stage.spread.complete',
        },
      },
      {
        id: 'coronation',
        title: 'Coronation of Abundance',
        descriptionKey: 'quest.main.coronation.stage.coronation.desc',
        approaches: [QUEST_APPROACH.GROWTH, QUEST_APPROACH.CONVERSION],
        objectives: [
          {
            id: 'player_stage_8',
            label: 'Ascend to Leviathan size (stage 8+)',
            type: OBJECTIVE_TYPE.PLAYER_STAGE_MIN,
            stage: 8,
            count: 1,
          },
          {
            id: 'convert_cradle',
            label: 'Convert or defeat the cradle\'s famine spirits',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            regionId: 'gorgara_cradle',
            enemyId: 'famine_hag',
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 40, xp: 200, xpSource: 'major_story' },
          textKey: 'quest.main.coronation.stage.coronation.complete',
        },
      },
    ],

    endings: [
      {
        id: 'avatar_of_gorgara',
        label: 'Avatar of the Fat Goddess',
        condition: { minScores: { [QUEST_SCORE.ABUNDANCE]: 5 } },
        rewards: {
          ap: 80,
          xp: 800,
          xpSource: 'major_story',
          playerSizeCapBonus: 2,
          worldFlags: { gorgara_avatar: true, main_act3_complete: true },
          playerFlags: { leviathan_coronation: true },
        },
        textKey: 'quest.main.coronation.ending.avatar',
      },
      {
        id: 'herald_of_feast',
        label: 'Herald of the Eternal Feast',
        condition: { minScores: { [QUEST_SCORE.CONVERSION]: 3 } },
        rewards: {
          ap: 70,
          xp: 750,
          xpSource: 'major_story',
          playerSizeCapBonus: 1,
          worldFlags: { feast_herald: true, main_act3_complete: true },
        },
        textKey: 'quest.main.coronation.ending.herald',
      },
    ],

    rewards: {
      ap: 50,
      xp: 600,
      xpSource: 'major_story',
      worldFlags: { main_act3_complete: true },
      unlockRegions: ['gorgara_cradle'],
      textKey: 'quest.main.coronation.complete.default',
    },
  },
];
