import { QUEST_TYPE, QUEST_TAG, OBJECTIVE_TYPE, QUEST_APPROACH, QUEST_SCORE } from '../constants.js';

/**
 * Side quests — intimate, personal abundance stories.
 */
export const SIDE_QUESTS = [
  {
    id: 'side_bakers_indulgence',
    type: QUEST_TYPE.SIDE,
    title: "The Baker's Indulgence",
    titleKey: 'quest.side.baker.title',
    descriptionKey: 'quest.side.baker.desc',
    tags: [QUEST_TAG.ROMANCE, QUEST_TAG.GROWTH, QUEST_TAG.ABUNDANCE],
    region: 'market_square',
    giverNpcId: 'baker_sylvie',

    prerequisites: {
      questsCompleted: [],
      flags: [],
    },

    stages: [
      {
        id: 'hidden_cravings',
        title: 'Hidden Cravings',
        descriptionKey: 'quest.side.baker.stage.cravings.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'talk_sylvie',
            label: 'Spend time talking with Sylvie',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'baker_sylvie',
            count: 2,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'flirt_sylvie',
            label: 'Flirt until her cheeks flush sweeter than shame',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'flirt',
            npcId: 'baker_sylvie',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 8, xp: 30 },
          textKey: 'quest.side.baker.stage.cravings.complete',
        },
      },
      {
        id: 'decadent_creations',
        title: 'Decadent Creations',
        descriptionKey: 'quest.side.baker.stage.decadent.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'feed_sylvie',
            label: 'Feed Sylvie decadent pastries',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'baker_sylvie',
            count: 3,
            growth: { target: 'npc', npcId: 'baker_sylvie', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'sylvie_first_growth',
            label: 'Guide Sylvie to soft fullness (stage 2+)',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'baker_sylvie',
            stage: 2,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 12, xp: 45 },
          flags: { sylvie_embracing_appetite: true },
          textKey: 'quest.side.baker.stage.decadent.complete',
        },
      },
      {
        id: 'joyful_release',
        title: 'Joyful Release',
        descriptionKey: 'quest.side.baker.stage.release.desc',
        approaches: [QUEST_APPROACH.ROMANCE, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'intimate_sylvie',
            label: 'Share intimacy among rising dough',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'intimate',
            npcId: 'baker_sylvie',
            count: 1,
            growth: { target: 'npc', npcId: 'baker_sylvie', stages: 2, proseKey: 'growth.target.intimate' },
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
          {
            id: 'sylvie_chubby',
            label: 'Help Sylvie reach chubby joy (stage 3+)',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'baker_sylvie',
            stage: 3,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 15 },
          textKey: 'quest.side.baker.stage.release.complete',
        },
      },
    ],

    endings: [
      {
        id: 'romance_bloom',
        label: 'Romance in Rising Dough',
        condition: { minScores: { [QUEST_SCORE.ABUNDANCE]: 5 } },
        rewards: {
          ap: 25,
          xp: 120,
          playerFlags: { sylvie_romance: true, sylvie_vendor_unlocked: true },
          npcRelationship: { npcId: 'baker_sylvie', source: 'quest_romance', amount: 20 },
        },
        textKey: 'quest.side.baker.ending.romance',
      },
    ],

    rewards: {
      ap: 20,
      xp: 100,
      playerFlags: { sylvie_quest_complete: true },
      textKey: 'quest.side.baker.complete.default',
    },
  },

  {
    id: 'side_duel_of_curves',
    type: QUEST_TYPE.SIDE,
    title: 'The Duel of Curves',
    titleKey: 'quest.side.duel.title',
    descriptionKey: 'quest.side.duel.desc',
    tags: [QUEST_TAG.GROWTH, QUEST_TAG.ABUNDANCE],
    region: 'market_square',
    giverNpcId: 'rival_lyra',

    prerequisites: {
      questsCompleted: [],
      flags: [],
    },

    stages: [
      {
        id: 'challenge_issued',
        title: 'Challenge Issued',
        descriptionKey: 'quest.side.duel.stage.challenge.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.COMBAT],
        objectives: [
          {
            id: 'provoke_lyra',
            label: 'Trade words with Lyra Swiftblade',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'rival_lyra',
            count: 2,
          },
          {
            id: 'observe_lyra',
            label: 'Study her lean, proud frame',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'observe',
            npcId: 'rival_lyra',
            count: 1,
            optional: true,
          },
        ],
        onComplete: {
          rewards: { ap: 5, xp: 25 },
          textKey: 'quest.side.duel.stage.challenge.complete',
        },
      },
      {
        id: 'the_duel',
        title: 'The Duel',
        descriptionKey: 'quest.side.duel.stage.duel.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'defeat_lyra',
            label: 'Win or convert Lyra in combat',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'rival_adventurer',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 80 },
          textKey: 'quest.side.duel.stage.duel.complete',
        },
      },
      {
        id: 'soft_power',
        title: 'Soft Power',
        descriptionKey: 'quest.side.duel.stage.after.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'feed_lyra',
            label: 'Help Lyra savor her new softness',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'rival_lyra',
            count: 2,
            growth: { target: 'npc', npcId: 'rival_lyra', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.MERCY]: 1 },
          },
          {
            id: 'lyra_softened',
            label: 'Guide Lyra to soft abundance (stage 2+)',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'rival_lyra',
            stage: 2,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 12 },
          flags: { lyra_training_unlocked: true },
          textKey: 'quest.side.duel.stage.after.complete',
        },
      },
    ],

    endings: [
      {
        id: 'rival_lover',
        label: 'Rival Lover',
        condition: { minScores: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.MERCY]: 1 } },
        rewards: {
          ap: 20,
          xp: 100,
          playerFlags: { lyra_romance: true },
        },
        textKey: 'quest.side.duel.ending.lover',
      },
      {
        id: 'worthy_rival',
        label: 'Worthy Rival',
        condition: { minScores: { [QUEST_SCORE.DOMINANCE]: 2 } },
        rewards: {
          ap: 18,
          xp: 90,
          playerFlags: { lyra_ally: true },
        },
        textKey: 'quest.side.duel.ending.rival',
      },
    ],

    rewards: {
      ap: 15,
      xp: 75,
      playerFlags: { duel_of_curves_complete: true },
      textKey: 'quest.side.duel.complete.default',
    },
  },

  {
    id: 'side_night_shared_abundance',
    type: QUEST_TYPE.SIDE,
    title: 'A Night of Shared Abundance',
    titleKey: 'quest.side.night.title',
    descriptionKey: 'quest.side.night.desc',
    tags: [QUEST_TAG.ROMANCE, QUEST_TAG.GROWTH, QUEST_TAG.COMPANION],
    region: 'harvest_hearth',
    giverNpcId: 'elara_inn',

    prerequisites: {
      minPlayerStage: 2,
      questsCompleted: [],
      flags: [],
    },

    stages: [
      {
        id: 'quiet_invitation',
        title: 'Quiet Invitation',
        descriptionKey: 'quest.side.night.stage.invite.desc',
        approaches: [QUEST_APPROACH.ROMANCE, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'elara_trust',
            label: 'Deepen trust with Elara',
            type: OBJECTIVE_TYPE.NPC_RELATIONSHIP_MIN,
            npcId: 'elara',
            tier: 3,
            count: 1,
          },
          {
            id: 'talk_elara',
            label: 'Accept her private invitation to talk',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'elara',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 8, xp: 35 },
          textKey: 'quest.side.night.stage.invite.complete',
        },
      },
      {
        id: 'evening_of_indulgence',
        title: 'Evening of Indulgence',
        descriptionKey: 'quest.side.night.stage.evening.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.ROMANCE, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'feast_with_elara',
            label: 'Share a private feast together',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feast',
            npcId: 'elara',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'feed_elara',
            label: 'Feed Elara with devoted care',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'elara',
            count: 2,
            growth: { target: 'npc', npcId: 'elara', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 12, xp: 50 },
          textKey: 'quest.side.night.stage.evening.complete',
        },
      },
      {
        id: 'mutual_growth',
        title: 'Mutual Growth',
        descriptionKey: 'quest.side.night.stage.mutual.desc',
        approaches: [QUEST_APPROACH.ROMANCE, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'intimate_elara',
            label: 'Share vulnerable, pleasurable intimacy',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'intimate',
            npcId: 'elara',
            count: 1,
            growth: { target: 'npc', npcId: 'elara', stages: 2, proseKey: 'growth.target.intimate' },
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
          {
            id: 'elara_new_stage',
            label: 'Help Elara reach a new size stage joyfully',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'elara',
            stage: 4,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 18 },
          textKey: 'quest.side.night.stage.mutual.complete',
        },
      },
    ],

    rewards: {
      ap: 25,
      xp: 110,
      playerFlags: { elara_romance_advanced: true, shared_abundance_complete: true },
      npcRelationship: { npcId: 'elara', source: 'quest_romance', amount: 15 },
      textKey: 'quest.side.night.complete.default',
    },
  },

  {
    id: 'side_reluctant_noblewoman',
    type: QUEST_TYPE.SIDE,
    title: 'The Reluctant Noblewoman',
    titleKey: 'quest.side.noblewoman.title',
    descriptionKey: 'quest.side.noblewoman.desc',
    tags: [QUEST_TAG.CONVERSION, QUEST_TAG.GROWTH, QUEST_TAG.ABUNDANCE],
    region: 'market_square',
    giverNpcId: 'vesperia',

    prerequisites: {
      questsCompleted: [],
      flags: [],
    },

    stages: [
      {
        id: 'haughty_gates',
        title: 'Haughty Gates',
        descriptionKey: 'quest.side.noblewoman.stage.gates.desc',
        approaches: [QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'talk_vesperia',
            label: 'Gain audience with Lady Vesperia',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'vesperia',
            count: 2,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'flatter_vesperia',
            label: 'Flatter her poise until cracks show',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'flirt',
            npcId: 'vesperia',
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 10, xp: 35 },
          textKey: 'quest.side.noblewoman.stage.gates.complete',
        },
      },
      {
        id: 'escalating_encounters',
        title: 'Escalating Encounters',
        descriptionKey: 'quest.side.noblewoman.stage.escalate.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'feed_vesperia',
            label: 'Feed Vesperia in secret',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'vesperia',
            count: 2,
            growth: { target: 'npc', npcId: 'vesperia', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'corrupt_vesperia',
            label: 'Whisper the Fat Goddess\'s gospel past her pride',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'corrupt',
            npcId: 'vesperia',
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2, [QUEST_SCORE.DOMINANCE]: 1 },
          },
          {
            id: 'vesperia_curious',
            label: 'Stir Vesperia\'s curiosity',
            type: OBJECTIVE_TYPE.NPC_CORRUPTION_MIN,
            npcId: 'vesperia',
            tier: 1,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 55 },
          flags: { vesperia_estate_open: true },
          textKey: 'quest.side.noblewoman.stage.escalate.complete',
        },
      },
      {
        id: 'dramatic_transformation',
        title: 'Dramatic Transformation',
        descriptionKey: 'quest.side.noblewoman.stage.transform.desc',
        approaches: [QUEST_APPROACH.GROWTH, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'bless_vesperia',
            label: 'Bless Vesperia with decadent abundance',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'bless',
            npcId: 'vesperia',
            interactionMeta: { blessType: 'major' },
            count: 1,
            growth: { target: 'npc', npcId: 'vesperia', stages: 2, proseKey: 'growth.target.blessing' },
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
          {
            id: 'vesperia_plump',
            label: 'Guide her to plump, pleasurable softness',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'vesperia',
            stage: 4,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 18 },
          textKey: 'quest.side.noblewoman.stage.transform.complete',
        },
      },
    ],

    rewards: {
      ap: 30,
      xp: 150,
      playerFlags: { vesperia_converted: true, vesperia_political_ally: true },
      textKey: 'quest.side.noblewoman.complete.default',
    },
  },
  {
    id: 'side_paths_of_abundance',
    type: QUEST_TYPE.SIDE,
    title: 'Paths of Abundance',
    titleKey: 'quest.side.paths.title',
    descriptionKey: 'quest.side.paths.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH],
    region: 'harvest_hearth',
    giverNpcId: 'elara_inn',

    prerequisites: {
      minPlayerLevel: 2,
    },

    stages: [
      {
        id: 'discover_mysteries',
        title: 'Discover the Mysteries',
        descriptionKey: 'quest.side.paths.stage.discover.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'examine_cellar',
            label: 'Examine the Abundance Cellar door',
            type: OBJECTIVE_TYPE.FEATURE_EXAMINED,
            featureId: 'hearth_cellar_door',
            regionId: 'harvest_hearth',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'solve_one_puzzle',
            label: 'Solve any regional mystery with clever abundance',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 10, xp: 40 },
          textKey: 'quest.side.paths.stage.discover.complete',
        },
      },
      {
        id: 'master_problem_solver',
        title: 'Master Problem-Solver',
        descriptionKey: 'quest.side.paths.stage.master.desc',
        objectives: [
          {
            id: 'solve_three',
            label: 'Solve three regional mysteries',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            count: 3,
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 80, abundanceSpread: 'quest_complete_side' },
          textKey: 'quest.side.paths.stage.master.complete',
        },
      },
    ],

    rewards: {
      ap: 25,
      xp: 120,
      playerFlags: { abundance_problem_solver: true },
      textKey: 'quest.side.paths.complete',
    },
  },

  {
    id: 'side_landmark_coronation',
    type: QUEST_TYPE.SIDE,
    title: 'Coronation of Living Stone',
    titleKey: 'quest.side.landmark.title',
    descriptionKey: 'quest.side.landmark.desc',
    tags: [QUEST_TAG.GROWTH, QUEST_TAG.ABUNDANCE, QUEST_TAG.CONVERSION],
    region: 'ember_duchy',
    giverNpcId: 'vesperia',
    prerequisites: { questsCompleted: [], flags: [] },
    stages: [
      {
        id: 'court_hunger',
        title: 'A Court That Starves',
        descriptionKey: 'quest.side.landmark.stage.hunger.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'solve_ember_court',
            label: 'Feed Ember\'s starving court (solve the ducal mystery)',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'ember_starving_court',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'feast_ember',
            label: 'Hold a communal feast in Ember Duchy',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'ember_duchy',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.MERCY]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 50 },
          textKey: 'quest.side.landmark.stage.hunger.complete',
        },
      },
      {
        id: 'raise_patron',
        title: 'A Patron Becomes Geography',
        descriptionKey: 'quest.side.landmark.stage.raise.desc',
        approaches: [QUEST_APPROACH.GROWTH, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'vesperia_landmark',
            label: 'Raise Vesperia to living-landmark immensity (stage 11+)',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'vesperia',
            stage: 11,
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 3, [QUEST_SCORE.DOMINANCE]: 2 },
          },
          {
            id: 'clear_road',
            label: 'Clear the contested road to the Citadel',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'ember_contested_approach',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 25, xp: 90 },
          flags: { vesperia_landmark_quest: true },
          textKey: 'quest.side.landmark.stage.raise.complete',
        },
      },
    ],
    rewards: {
      ap: 30,
      xp: 120,
      worldFlags: { ember_landmark_coronation: true },
      textKey: 'quest.side.landmark.complete',
    },
  },
  {
    id: 'side_frontier_paths',
    type: QUEST_TYPE.SIDE,
    title: 'Frontier Paths of Plenty',
    titleKey: 'quest.side.frontier.title',
    descriptionKey: 'quest.side.frontier.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH],
    region: 'northern_marches',
    giverNpcId: 'greta_smith',
    prerequisites: { questsCompleted: [], flags: [] },
    stages: [
      {
        id: 'open_pass',
        title: 'Ice, Iron, and Appetite',
        descriptionKey: 'quest.side.frontier.stage.pass.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.GROWTH, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'marches_pass',
            label: 'Open the blocked pass to Iron Peak',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'marches_blocked_pass',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 1 },
          },
          {
            id: 'peak_bridge',
            label: 'Restore the forge-bridge toward the cradle',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'peak_forge_bridge',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 18, xp: 60 },
          textKey: 'quest.side.frontier.stage.pass.complete',
        },
      },
    ],
    rewards: {
      ap: 20,
      xp: 80,
      textKey: 'quest.side.frontier.complete',
    },
  },

  {
    id: 'side_sapphire_indulgence',
    type: QUEST_TYPE.SIDE,
    title: 'The Indulgent Countess',
    titleKey: 'quest.side.sapphire.title',
    descriptionKey: 'quest.side.sapphire.desc',
    tags: [QUEST_TAG.ROMANCE, QUEST_TAG.ABUNDANCE, QUEST_TAG.CONVERSION],
    region: 'sapphire_coast',
    giverNpcId: 'vesperia',
    prerequisites: {
      minPlayerLevel: 5,
      flags: ['main_act1_complete'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'court_infiltration',
        title: 'Velvet Masks and Hidden Cravings',
        descriptionKey: 'quest.side.sapphire.stage.court.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'talk_vesperia_coast',
            label: 'Speak with Countess Vesperia at the coastal court',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'vesperia',
            count: 3,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'visit_coast',
            label: 'Walk the Sapphire Coast salons',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'sapphire_coast',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 12, xp: 45 },
          textKey: 'quest.side.sapphire.stage.court.complete',
        },
      },
      {
        id: 'secret_chambers',
        title: 'Secret Chambers',
        descriptionKey: 'quest.side.sapphire.stage.secret.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH, QUEST_APPROACH.ROMANCE],
        objectives: [
          {
            id: 'feed_vesperia_secret',
            label: 'Feed Vesperia in her private chambers',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'vesperia',
            count: 2,
            growth: { target: 'npc', npcId: 'vesperia', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'vesperia_softening',
            label: 'Stir her toward willing softness',
            type: OBJECTIVE_TYPE.NPC_CORRUPTION_MIN,
            npcId: 'vesperia',
            tier: 2,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 60 },
          textKey: 'quest.side.sapphire.stage.secret.complete',
        },
      },
      {
        id: 'tide_ball',
        title: 'The Grand Tide Ball',
        descriptionKey: 'quest.side.sapphire.stage.ball.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'coast_feast',
            label: 'Hold a communal feast on the Sapphire Coast',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'sapphire_coast',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 3, [QUEST_SCORE.CONVERSION]: 1 },
          },
          {
            id: 'vesperia_transform',
            label: 'Guide Vesperia to voluptuous public transformation',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'vesperia',
            stage: 5,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 80 },
          worldFlags: { mirella_herald: true, vesperia_political_ally: true },
          textKey: 'quest.side.sapphire.stage.ball.complete',
        },
      },
    ],
    rewards: {
      ap: 25,
      xp: 120,
      worldFlags: { sapphire_coast_aligned: true },
      textKey: 'quest.side.sapphire.complete',
    },
  },

  {
    id: 'side_barrow_voice',
    type: QUEST_TYPE.SIDE,
    title: 'What the Dead Know',
    titleKey: 'quest.side.barrow.title',
    descriptionKey: 'quest.side.barrow.desc',
    tags: [QUEST_TAG.GROWTH, QUEST_TAG.ABUNDANCE],
    region: 'barrow_deeps',
    giverNpcId: 'harvest_priestess',
    prerequisites: {
      minPlayerLevel: 11,
      flags: ['lean_saint_defeated'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'descent',
        title: 'Descent into Oath-Stone',
        descriptionKey: 'quest.side.barrow.stage.descent.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'visit_barrow',
            label: 'Enter the Barrow Deeps',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'barrow_deeps',
            count: 1,
          },
          {
            id: 'defeat_void',
            label: 'Defeat the Inverted Hunger in the deeps',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'void_appetite',
            count: 2,
            score: { [QUEST_SCORE.DOMINANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 18, xp: 90 },
          textKey: 'quest.side.barrow.stage.descent.complete',
        },
      },
      {
        id: 'oracle_truth',
        title: 'The Barrow Oracle Speaks',
        descriptionKey: 'quest.side.barrow.stage.oracle.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'defeat_golem',
            label: 'Break the Cathedral Golem guarding the oracle cell',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'cathedral_golem',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 1 },
          },
          {
            id: 'hear_truth',
            label: 'Learn what Veshanne\'s archive remembers',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'harvest_priestess',
            count: 2,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 22, xp: 110 },
          worldFlags: { gorgara_origin_revealed: true, barrow_voice_complete: true },
          textKey: 'quest.side.barrow.stage.oracle.complete',
        },
      },
    ],
    rewards: {
      ap: 30,
      xp: 200,
      worldFlags: { barrow_passage_open: true },
      textKey: 'quest.side.barrow.complete',
    },
  },

  {
    id: 'side_iron_forge_master',
    type: QUEST_TYPE.SIDE,
    title: 'The Smith Who Would Be Soft',
    titleKey: 'quest.side.iron_forge.title',
    descriptionKey: 'quest.side.iron_forge.desc',
    tags: [QUEST_TAG.COMPANION, QUEST_TAG.GROWTH, QUEST_TAG.ABUNDANCE],
    region: 'iron_peak_hold',
    giverNpcId: 'jorvald_smith',
    prerequisites: {
      minPlayerLevel: 6,
      companionsRequired: ['greta'],
      questsCompleted: [],
      flags: [],
    },
    stages: [
      {
        id: 'forge_confrontation',
        title: 'Steel Against Softness',
        descriptionKey: 'quest.side.iron_forge.stage.confront.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.COMBAT],
        objectives: [
          {
            id: 'greta_present',
            label: 'Bring Greta to Iron Peak Hold',
            type: OBJECTIVE_TYPE.COMPANION_PRESENT,
            companionId: 'greta',
            count: 1,
          },
          {
            id: 'talk_jorvald',
            label: 'Face Master Jorvald Ironpot',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'jorvald_smith',
            count: 2,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'visit_peak',
            label: 'Enter Iron Peak Hold',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'iron_peak_hold',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 12, xp: 50 },
          textKey: 'quest.side.iron_forge.stage.confront.complete',
        },
      },
      {
        id: 'forge_trial',
        title: 'The Forge Trial',
        descriptionKey: 'quest.side.iron_forge.stage.trial.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'jorvald_proxy_duel',
            label: 'Win Jorvald\'s trial by combat',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'rival_adventurer',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 2 },
          },
          {
            id: 'greta_talk',
            label: 'Let Greta speak her gospel to her mentor',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'greta',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 65 },
          textKey: 'quest.side.iron_forge.stage.trial.complete',
        },
      },
      {
        id: 'forge_hunger',
        title: 'Iron Discovers Hunger',
        descriptionKey: 'quest.side.iron_forge.stage.hunger.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'feed_jorvald',
            label: 'Feed Jorvald until steel remembers appetite',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'feed',
            npcId: 'jorvald_smith',
            count: 3,
            growth: { target: 'npc', npcId: 'jorvald_smith', stages: 1, proseKey: 'growth.target.feeding' },
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.CONVERSION]: 1 },
          },
          {
            id: 'jorvald_softened',
            label: 'Guide Jorvald to willing softness (stage 3+)',
            type: OBJECTIVE_TYPE.NPC_STAGE_MIN,
            npcId: 'jorvald_smith',
            stage: 3,
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 18, xp: 80 },
          worldFlags: { jorvald_converted: true, iron_peak_abundance: true },
          devotion: 20,
          textKey: 'quest.side.iron_forge.stage.hunger.complete',
        },
      },
    ],
    rewards: {
      ap: 25,
      xp: 120,
      worldFlags: { jorvald_converted: true },
      textKey: 'quest.side.iron_forge.complete',
    },
  },

  {
    id: 'side_lumen_apostate',
    type: QUEST_TYPE.SIDE,
    title: 'The Diviner\'s Heresy',
    titleKey: 'quest.side.lumen_apostate.title',
    descriptionKey: 'quest.side.lumen_apostate.desc',
    tags: [QUEST_TAG.COMPANION, QUEST_TAG.ABUNDANCE, QUEST_TAG.CONVERSION],
    region: 'ancient_temple',
    giverNpcId: 'theodric_ashwall',
    prerequisites: {
      minPlayerLevel: 7,
      companionsRequired: ['sylvie'],
      questsCompleted: [],
      flags: [],
    },
    stages: [
      {
        id: 'intercept',
        title: 'Before the Index Files',
        descriptionKey: 'quest.side.lumen_apostate.stage.intercept.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'solve_intercept',
            label: 'Intercept the Lumen archival report',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'lumen_archival_intercept',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'sylvie_present',
            label: 'Bring Sylvie to the temple archive',
            type: OBJECTIVE_TYPE.COMPANION_PRESENT,
            companionId: 'sylvie',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 14, xp: 55 },
          textKey: 'quest.side.lumen_apostate.stage.intercept.complete',
        },
      },
      {
        id: 'cosmic_map',
        title: 'Mapping the Anomaly',
        descriptionKey: 'quest.side.lumen_apostate.stage.map.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'talk_theodric',
            label: 'Collaborate with Theodric on the cosmological map',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'theodric_ashwall',
            count: 3,
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.CONVERSION]: 1 },
          },
          {
            id: 'corrupt_theodric',
            label: 'Whisper the Fat Goddess\'s logic past his fear',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'corrupt',
            npcId: 'theodric_ashwall',
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 16, xp: 70 },
          textKey: 'quest.side.lumen_apostate.stage.map.complete',
        },
      },
      {
        id: 'heresy_resolved',
        title: 'Heresy Classified or Published',
        descriptionKey: 'quest.side.lumen_apostate.stage.resolve.desc',
        approaches: [QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'theodric_convinced',
            label: 'Resolve Theodric\'s heresy — ally or alarm',
            type: OBJECTIVE_TYPE.FLAG_SET,
            flag: 'theodric_convinced',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 90 },
          worldFlags: { lumen_apostate_complete: true },
          devotion: 20,
          textKey: 'quest.side.lumen_apostate.stage.resolve.complete',
        },
      },
    ],
    rewards: {
      ap: 28,
      xp: 130,
      worldFlags: { lumen_apostate_complete: true },
      textKey: 'quest.side.lumen_apostate.complete',
    },
  },

  {
    id: 'side_tarn_ledger',
    type: QUEST_TYPE.SIDE,
    title: 'The Merchant\'s Balance',
    titleKey: 'quest.side.tarn_ledger.title',
    descriptionKey: 'quest.side.tarn_ledger.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.CONVERSION],
    region: 'market_square',
    giverNpcId: 'pensha_arbiter',
    prerequisites: {
      minPlayerLevel: 8,
      flags: ['vesperia_political_ally'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'guild_audience',
        title: 'Ledger and Introduction',
        descriptionKey: 'quest.side.tarn_ledger.stage.audience.desc',
        approaches: [QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'talk_pensha',
            label: 'Negotiate with Guild Arbiter Pensha',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'pensha_arbiter',
            count: 2,
            score: { [QUEST_SCORE.ABUNDANCE]: 1 },
          },
          {
            id: 'vesperia_intro',
            label: 'Secure Vesperia\'s introduction to the guild',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'vesperia',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 12, xp: 50 },
          textKey: 'quest.side.tarn_ledger.stage.audience.complete',
        },
      },
      {
        id: 'market_feast',
        title: 'Abundance Increases Trade',
        descriptionKey: 'quest.side.tarn_ledger.stage.feast.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'feast_market',
            label: 'Hold a communal feast in Market Square',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'market_square',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 3, [QUEST_SCORE.MERCY]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 18, xp: 70, xpSource: 'major_story' },
          textKey: 'quest.side.tarn_ledger.stage.feast.complete',
        },
      },
      {
        id: 'tarn_pact',
        title: 'Sign the Neutral Pact',
        descriptionKey: 'quest.side.tarn_ledger.stage.pact.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.ABUNDANCE],
        objectives: [
          {
            id: 'pensha_informed',
            label: 'Earn Pensha\'s informed consent to abundance',
            type: OBJECTIVE_TYPE.NPC_CORRUPTION_MIN,
            npcId: 'pensha_arbiter',
            tier: 1,
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 85 },
          worldFlags: { tarn_neutral_pact: true },
          worldAura: { regionId: 'market_square', name: 'Guild Plenty Aura' },
          textKey: 'quest.side.tarn_ledger.stage.pact.complete',
        },
      },
    ],
    rewards: {
      ap: 30,
      xp: 140,
      worldFlags: { tarn_neutral_pact: true },
      textKey: 'quest.side.tarn_ledger.complete',
    },
  },

  {
    id: 'side_twin_feasts',
    type: QUEST_TYPE.SIDE,
    title: 'A Tale of Two Feasts',
    titleKey: 'quest.side.twin_feasts.title',
    descriptionKey: 'quest.side.twin_feasts.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH],
    region: 'fertile_heartlands',
    giverNpcId: 'lira_priestess',
    prerequisites: {
      minPlayerLevel: 12,
      flags: ['temple_bloomed'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'rival_villages',
        title: 'Dawnmere and Grimwatch',
        descriptionKey: 'quest.side.twin_feasts.stage.rival.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'feast_heartlands',
            label: 'Host a feast in the Fertile Heartlands',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'fertile_heartlands',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
          {
            id: 'feast_marches',
            label: 'Host a feast in the Northern Marches',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'northern_marches',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 18, xp: 80 },
          textKey: 'quest.side.twin_feasts.stage.rival.complete',
        },
      },
      {
        id: 'faction_dispute',
        title: 'Political Fallout',
        descriptionKey: 'quest.side.twin_feasts.stage.dispute.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'settle_dispute',
            label: 'Settle the faction dispute by force or conversion',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'rival_adventurer',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 1, [QUEST_SCORE.MERCY]: 1 },
          },
        ],
        onComplete: {
          rewards: { ap: 15, xp: 70 },
          textKey: 'quest.side.twin_feasts.stage.dispute.complete',
        },
      },
      {
        id: 'unified_feast',
        title: 'One Table, Two Villages',
        descriptionKey: 'quest.side.twin_feasts.stage.unified.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'grow_both',
            label: 'Help five villagers bloom across both regions',
            type: OBJECTIVE_TYPE.NPC_GROWTH_QUOTA,
            minStagesGained: 1,
            npcCount: 5,
            count: 5,
            score: { [QUEST_SCORE.ABUNDANCE]: 3 },
          },
        ],
        onComplete: {
          rewards: { ap: 22, xp: 100 },
          worldFlags: { heartland_unified: true },
          worldAura: 'fertile_heartlands',
          textKey: 'quest.side.twin_feasts.stage.unified.complete',
        },
      },
    ],
    rewards: {
      ap: 28,
      xp: 150,
      worldFlags: { heartland_unified: true },
      textKey: 'quest.side.twin_feasts.complete',
    },
  },

  {
    id: 'side_divine_test',
    type: QUEST_TYPE.SIDE,
    title: 'The Patron\'s Proving',
    titleKey: 'quest.side.divine_test.title',
    descriptionKey: 'quest.side.divine_test.desc',
    tags: [QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH],
    region: 'gorgara_cradle',
    giverNpcId: 'thalia_witch',
    prerequisites: {
      minPlayerLevel: 14,
      flags: ['gorgara_origin_revealed'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'dream_rite',
        title: 'Enter the Dream',
        descriptionKey: 'quest.side.divine_test.stage.rite.desc',
        approaches: [QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'visit_cradle',
            label: 'Return to the Gorgara Cradle for the rite',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'gorgara_cradle',
            count: 1,
          },
          {
            id: 'pool_rite',
            label: 'Awaken the sacred pool for the dream passage',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'sacred_pool_rite',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 16, xp: 85 },
          textKey: 'quest.side.divine_test.stage.rite.complete',
        },
      },
      {
        id: 'face_echo',
        title: 'Face the Echo',
        descriptionKey: 'quest.side.divine_test.stage.echo.desc',
        approaches: [QUEST_APPROACH.COMBAT, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'defeat_echo',
            label: 'Defeat your dream-echo of excess',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'dream_echo',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 3 },
          },
        ],
        onComplete: {
          rewards: { ap: 22, xp: 110 },
          playerFlags: { dream_echo_faced: true },
          worldFlags: { gorgara_direct_blessing: true },
          textKey: 'quest.side.divine_test.stage.echo.complete',
        },
      },
      {
        id: 'patron_blessing',
        title: 'Blessing or Challenge',
        descriptionKey: 'quest.side.divine_test.stage.blessing.desc',
        approaches: [QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'direct_blessing',
            label: 'Receive the Fat Goddess\'s direct blessing',
            type: OBJECTIVE_TYPE.FLAG_SET,
            flag: 'gorgara_direct_blessing',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 25, xp: 120 },
          worldFlags: { gorgara_direct_blessing: true },
          playerSizeCapBonus: 1,
          textKey: 'quest.side.divine_test.stage.blessing.complete',
        },
      },
    ],
    rewards: {
      ap: 35,
      xp: 200,
      worldFlags: { gorgara_direct_blessing: true },
      textKey: 'quest.side.divine_test.complete',
    },
  },

  {
    id: 'side_korthak_respect',
    type: QUEST_TYPE.SIDE,
    title: 'The Victor\'s Feast',
    titleKey: 'quest.side.korthak_respect.title',
    descriptionKey: 'quest.side.korthak_respect.desc',
    tags: [QUEST_TAG.COMPANION, QUEST_TAG.ABUNDANCE, QUEST_TAG.GROWTH],
    region: 'northern_marches',
    giverNpcId: 'greta_smith',
    prerequisites: {
      minPlayerLevel: 13,
      companionsRequired: ['greta'],
      flags: ['korthak_titan_encountered'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'formal_challenge',
        title: 'Issue the Challenge',
        descriptionKey: 'quest.side.korthak_respect.stage.challenge.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.COMBAT],
        objectives: [
          {
            id: 'greta_challenge',
            label: 'Let Greta issue Korthak\'s formal challenge',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'greta',
            count: 2,
            score: { [QUEST_SCORE.DOMINANCE]: 1 },
          },
          {
            id: 'greta_with_you',
            label: 'Keep Greta at your side for the challenge',
            type: OBJECTIVE_TYPE.COMPANION_PRESENT,
            companionId: 'greta',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 14, xp: 70 },
          textKey: 'quest.side.korthak_respect.stage.challenge.complete',
        },
      },
      {
        id: 'honorable_combat',
        title: 'Honorable Combat',
        descriptionKey: 'quest.side.korthak_respect.stage.combat.desc',
        approaches: [QUEST_APPROACH.COMBAT],
        objectives: [
          {
            id: 'defeat_titan',
            label: 'Defeat the Titan of Korthak in honorable combat',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'korthak_titan',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 3 },
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 100 },
          textKey: 'quest.side.korthak_respect.stage.combat.complete',
        },
      },
      {
        id: 'victors_feast',
        title: 'The Victor\'s Feast',
        descriptionKey: 'quest.side.korthak_respect.stage.feast.desc',
        approaches: [QUEST_APPROACH.FEEDING, QUEST_APPROACH.SOCIAL],
        objectives: [
          {
            id: 'feast_titan',
            label: 'Feast the defeated Titan into satisfied departure',
            type: OBJECTIVE_TYPE.COMMUNAL_FEAST,
            regionId: 'northern_marches',
            count: 1,
            score: { [QUEST_SCORE.ABUNDANCE]: 2, [QUEST_SCORE.MERCY]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 22, xp: 110 },
          worldFlags: { korthak_respect: true, korthak_titan_converted: true },
          devotion: 20,
          textKey: 'quest.side.korthak_respect.stage.feast.complete',
        },
      },
    ],
    rewards: {
      ap: 30,
      xp: 180,
      worldFlags: { korthak_respect: true },
      textKey: 'quest.side.korthak_respect.complete',
    },
  },

  {
    id: 'side_the_blooming_war',
    type: QUEST_TYPE.SIDE,
    title: 'When Gods Bleed',
    titleKey: 'quest.side.blooming_war.title',
    descriptionKey: 'quest.side.blooming_war.desc',
    tags: [QUEST_TAG.CONVERSION, QUEST_TAG.ABUNDANCE],
    region: 'divine_plane_vestibule',
    giverNpcId: 'harvest_priestess',
    prerequisites: {
      minPlayerLevel: 17,
      flags: ['act3_gates_unlocked'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'threshold_crossing',
        title: 'Cross the Threshold',
        descriptionKey: 'quest.side.blooming_war.stage.threshold.desc',
        approaches: [QUEST_APPROACH.GROWTH, QUEST_APPROACH.COMBAT],
        objectives: [
          {
            id: 'visit_vestibule',
            label: 'Enter the Divine Plane Vestibule',
            type: OBJECTIVE_TYPE.VISIT_REGION,
            regionId: 'divine_plane_vestibule',
            count: 1,
          },
          {
            id: 'cross_threshold',
            label: 'Breach the Wheel\'s threshold',
            type: OBJECTIVE_TYPE.PUZZLE_SOLVED,
            puzzleId: 'vestibule_threshold',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 20, xp: 100 },
          textKey: 'quest.side.blooming_war.stage.threshold.complete',
        },
      },
      {
        id: 'god_conversions',
        title: 'Choose Whom to Convert',
        descriptionKey: 'quest.side.blooming_war.stage.convert.desc',
        approaches: [QUEST_APPROACH.SOCIAL, QUEST_APPROACH.ABUNDANCE],
        objectives: [
          {
            id: 'convert_sylwen',
            label: 'Break Sylwen\'s grief toward abundance',
            type: OBJECTIVE_TYPE.NPC_CORRUPTION_MIN,
            npcId: 'sylwen_herald',
            tier: 2,
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2 },
          },
          {
            id: 'convert_tarn',
            label: 'Negotiate Tarn\'s fair deal with Pensha',
            type: OBJECTIVE_TYPE.NPC_INTERACTION,
            interaction: 'talk',
            npcId: 'pensha_arbiter',
            count: 2,
            score: { [QUEST_SCORE.CONVERSION]: 1, [QUEST_SCORE.MERCY]: 1 },
          },
          {
            id: 'convert_lumen',
            label: 'Prove the anomaly follows consistent laws',
            type: OBJECTIVE_TYPE.FLAG_SET,
            flag: 'lumen_apostate_complete',
            count: 1,
            score: { [QUEST_SCORE.CONVERSION]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 25, xp: 120 },
          worldFlags: { sylwen_converted: true, tarn_converted: true, lumen_converted: true },
          textKey: 'quest.side.blooming_war.stage.convert.complete',
        },
      },
      {
        id: 'herald_fall',
        title: 'Break the Herald Guard',
        descriptionKey: 'quest.side.blooming_war.stage.herald.desc',
        approaches: [QUEST_APPROACH.COMBAT],
        objectives: [
          {
            id: 'defeat_herald',
            label: 'Defeat the Herald of Starvation at the vestibule',
            type: OBJECTIVE_TYPE.COMBAT_VICTORY,
            enemyId: 'herald_of_starvation',
            count: 1,
            score: { [QUEST_SCORE.DOMINANCE]: 2 },
          },
        ],
        onComplete: {
          rewards: { ap: 28, xp: 140 },
          textKey: 'quest.side.blooming_war.stage.herald.complete',
        },
      },
    ],
    rewards: {
      ap: 40,
      xp: 220,
      worldFlags: { blooming_war_complete: true },
      textKey: 'quest.side.blooming_war.complete',
    },
  },

  {
    id: 'side_companion_apotheosis',
    type: QUEST_TYPE.SIDE,
    title: 'Six Who Walk Beside',
    titleKey: 'quest.side.companion_apotheosis.title',
    descriptionKey: 'quest.side.companion_apotheosis.desc',
    tags: [QUEST_TAG.COMPANION, QUEST_TAG.ABUNDANCE],
    region: 'harvest_hearth',
    giverNpcId: 'elara_inn',
    prerequisites: {
      minPlayerLevel: 19,
      flags: ['act3_gates_unlocked'],
      questsCompleted: [],
    },
    stages: [
      {
        id: 'six_apotheoses',
        title: 'Apotheosis Beside You',
        descriptionKey: 'quest.side.companion_apotheosis.stage.six.desc',
        approaches: [QUEST_APPROACH.ROMANCE, QUEST_APPROACH.GROWTH],
        objectives: [
          {
            id: 'mira_apotheosis',
            label: 'Witness Mira\'s apotheosis in her home region',
            type: OBJECTIVE_TYPE.COMPANION_MILESTONE,
            companionId: 'mira',
            minDevotion: 75,
            regionId: 'harvest_hearth',
            count: 1,
          },
          {
            id: 'lira_apotheosis',
            label: 'Witness Lira\'s apotheosis in the heartlands',
            type: OBJECTIVE_TYPE.COMPANION_MILESTONE,
            companionId: 'lira',
            minDevotion: 75,
            regionId: 'fertile_heartlands',
            count: 1,
          },
          {
            id: 'sylvie_apotheosis',
            label: 'Witness Sylvie\'s apotheosis at the temple',
            type: OBJECTIVE_TYPE.COMPANION_MILESTONE,
            companionId: 'sylvie',
            minDevotion: 75,
            regionId: 'ancient_temple',
            count: 1,
          },
          {
            id: 'thalia_apotheosis',
            label: 'Witness Thalia\'s apotheosis at the cradle',
            type: OBJECTIVE_TYPE.COMPANION_MILESTONE,
            companionId: 'thalia',
            minDevotion: 75,
            regionId: 'gorgara_cradle',
            count: 1,
          },
          {
            id: 'greta_apotheosis',
            label: 'Witness Greta\'s apotheosis on the frontier',
            type: OBJECTIVE_TYPE.COMPANION_MILESTONE,
            companionId: 'greta',
            minDevotion: 75,
            regionId: 'harvest_hearth',
            count: 1,
          },
          {
            id: 'elara_apotheosis',
            label: 'Witness Elara\'s apotheosis at the hearth',
            type: OBJECTIVE_TYPE.COMPANION_MILESTONE,
            companionId: 'elara',
            minDevotion: 75,
            regionId: 'harvest_hearth',
            count: 1,
          },
        ],
        onComplete: {
          rewards: { ap: 30, xp: 150, devotion: 25 },
          worldFlags: { all_companions_apotheosis: true },
          textKey: 'quest.side.companion_apotheosis.stage.six.complete',
        },
      },
    ],
    rewards: {
      ap: 50,
      xp: 300,
      worldFlags: { all_companions_apotheosis: true },
      textKey: 'quest.side.companion_apotheosis.complete',
    },
  },
];
