import { PUZZLE_TYPE, SOLUTION_KIND } from '../constants.js';

/**
 * Region puzzles — multiple valid solutions per obstacle.
 * stateFlag in worldFlags marks completion; examinedFlag tracks discovery.
 */
export const REGION_PUZZLES = [
  {
    id: 'cellar_abundance_vault',
    regionId: 'harvest_hearth',
    featureId: 'hearth_cellar_door',
    title: 'The Abundance Cellar',
    type: PUZZLE_TYPE.ENVIRONMENTAL,
    tightSpace: true,
    stateFlag: 'puzzle_cellar_vault_solved',
    examinedFlag: 'puzzle_cellar_vault_examined',
    desc: 'A heavy oak door seals Elara\'s legendary reserve cellar — pastries too sacred for ordinary hands.',
    solutions: [
      {
        id: 'grace_pick',
        label: 'Pick the lock with velvet patience',
        hint: 'Grace and finesse can coax stubborn wood.',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'grace',
        dc: 13,
        onSolve: {
          textKey: 'puzzle.solve.cellar_grace',
          rewards: { ap: 5, xp: 25 },
        },
      },
      {
        id: 'rich_cream_soften',
        label: 'Soften the wood with Rich Cream',
        hint: 'Abundance magic makes oak yield like warm butter.',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['rich_cream', 'softening_ray'],
        environmentTags: ['soften'],
        onSolve: {
          textKey: 'puzzle.solve.cellar_cream',
          rewards: { ap: 3, xp: 20 },
        },
      },
      {
        id: 'shoulder_door',
        label: 'Shoulder the door with plush mass',
        hint: 'A truly plump body turns stubborn timber into suggestion.',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 4,
        onSolve: {
          textKey: 'puzzle.solve.cellar_shoulder',
          rewards: { xp: 30 },
        },
      },
      {
        id: 'elara_key',
        label: 'Ask Elara for the cellar key',
        hint: 'A close bond with the innkeeper opens every pantry.',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'elara_inn',
        tier: 2,
        onSolve: {
          textKey: 'puzzle.solve.cellar_elara',
          rewards: { ap: 8 },
        },
      },
      {
        id: 'clear_scavengers',
        label: 'Drive off goblin scavengers in the cellar',
        hint: 'Sometimes abundance is claimed by force of appetite.',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'gluttonous_goblin',
        onSolve: {
          textKey: 'puzzle.solve.cellar_combat',
          rewards: { xp: 35 },
        },
      },
    ],
    onSolve: {
      worldFlags: { hearth_cellar_open: true },
    },
  },
  {
    id: 'vesperia_garden_gate',
    regionId: 'market_square',
    featureId: 'vesperia_iron_gate',
    title: 'Lady Vesperia\'s Iron Gate',
    type: PUZZLE_TYPE.SOCIAL,
    stateFlag: 'puzzle_vesperia_gate_solved',
    examinedFlag: 'puzzle_vesperia_gate_examined',
    desc: 'An ornate iron gate guards Vesperia\'s private garden of rare delicacies — only the charming or the clever pass.',
    solutions: [
      {
        id: 'persuade_guard',
        label: 'Persuade the gatekeeper with honeyed words',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'persuade',
        dc: 14,
        onSolve: {
          textKey: 'puzzle.solve.vesperia_persuade',
          rewards: { xp: 25 },
        },
      },
      {
        id: 'charm_spell',
        label: 'Charm the iron with enchantment',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['feasts_whisper', 'jiggle_charm', 'overflowing_charm', 'honeyed_overflow'],
        environmentTags: ['charm'],
        onSolve: {
          textKey: 'puzzle.solve.vesperia_charm',
          rewards: { xp: 30 },
        },
      },
      {
        id: 'vesperia_trust',
        label: 'Call upon Vesperia\'s growing trust',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'vesperia',
        tier: 2,
        onSolve: {
          textKey: 'puzzle.solve.vesperia_trust',
          rewards: { ap: 10 },
        },
      },
      {
        id: 'perform_distraction',
        label: 'Perform a dazzling distraction',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'perform',
        dc: 12,
        onSolve: {
          textKey: 'puzzle.solve.vesperia_perform',
          rewards: { xp: 20 },
        },
      },
      {
        id: 'duel_rival',
        label: 'Duel the rival blocking the garden path',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'rival_adventurer',
        onSolve: {
          textKey: 'puzzle.solve.vesperia_combat',
          rewards: { xp: 40 },
        },
      },
    ],
    onSolve: {
      worldFlags: { vesperia_garden_open: true },
    },
  },
  {
    id: 'choked_ravine',
    regionId: 'fertile_heartlands',
    featureId: 'swollen_ravine',
    title: 'The Swollen Ravine',
    type: PUZZLE_TYPE.TRAVERSAL,
    stateFlag: 'puzzle_choked_ravine_solved',
    examinedFlag: 'puzzle_choked_ravine_examined',
    desc: 'A gorge choked with overgrown vines and swollen fruit blocks the path toward Shrine of the Thin Veil.',
    gateId: 'gate_heartlands_cradle',
    solutions: [
      {
        id: 'living_bridge',
        label: 'Span the gorge with your living bridge of flesh',
        hint: 'Grow enormous — your body becomes the crossing.',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 6,
        onSolve: {
          textKey: 'puzzle.solve.ravine_bridge',
          rewards: { xp: 50 },
        },
      },
      {
        id: 'self_feed_grow',
        label: 'Self-feed until you can reach across',
        hint: 'Indulge yourself here and now — abundance answers hunger.',
        kind: SOLUTION_KIND.SELF_GROW,
        stages: 2,
        apCost: 10,
        minStage: 4,
        onSolve: {
          textKey: 'puzzle.solve.ravine_self_feed',
          rewards: { xp: 40 },
        },
      },
      {
        id: 'cream_slick',
        label: 'Flood the ravine with slick abundance',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['rich_cream', 'banquet_mist', 'glutinous_surge'],
        environmentTags: ['slick', 'soften', 'fertile'],
        onSolve: {
          textKey: 'puzzle.solve.ravine_cream',
          rewards: { xp: 35 },
        },
      },
      {
        id: 'lira_blessing',
        label: 'Ask Lira to bless a vine bridge',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'lira_priestess',
        tier: 2,
        onSolve: {
          textKey: 'puzzle.solve.ravine_lira',
          rewards: { ap: 8 },
        },
      },
      {
        id: 'endure_climb',
        label: 'Clamber through the swollen vines',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'endure_growth',
        dc: 15,
        onSolve: {
          textKey: 'puzzle.solve.ravine_climb',
          rewards: { xp: 30 },
        },
      },
      {
        id: 'fight_harpy_nest',
        label: 'Fight through the harpy nest choking the gorge',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'harvest_harpy',
        onSolve: {
          textKey: 'puzzle.solve.ravine_combat',
          rewards: { xp: 45 },
        },
      },
    ],
    onSolve: {
      unlockRegions: [],
      worldFlags: { ravine_crossed: true },
    },
  },
  {
    id: 'sacred_pool_rite',
    regionId: 'gorgara_cradle',
    featureId: 'gorgara_sacred_pool',
    title: 'The Sacred Pool of First Hunger',
    type: PUZZLE_TYPE.RITUAL,
    stateFlag: 'puzzle_sacred_pool_solved',
    examinedFlag: 'puzzle_sacred_pool_examined',
    desc: 'Golden water stirs in the grotto pool — it waits for abundance to be poured into the world before it reveals its depths.',
    solutions: [
      {
        id: 'abundance_offering',
        label: 'Offer your spreading abundance to the pool',
        kind: SOLUTION_KIND.ABUNDANCE_MIN,
        points: 50,
        onSolve: {
          textKey: 'puzzle.solve.pool_abundance',
          rewards: { ap: 15, xp: 40 },
        },
      },
      {
        id: 'banquet_mist_rite',
        label: 'Perfume the grotto with Banquet Mist',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['banquet_mist', 'feast_of_the_goddess', 'divine_plump'],
        environmentTags: ['fertile', 'ritual'],
        onSolve: {
          textKey: 'puzzle.solve.pool_mist',
          rewards: { xp: 45 },
        },
      },
      {
        id: 'indulge_rite',
        label: 'Perform the indulgence rite at the water\'s edge',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'indulge',
        dc: 14,
        onSolve: {
          textKey: 'puzzle.solve.pool_indulge',
          rewards: { xp: 35 },
        },
      },
      {
        id: 'thalia_guidance',
        label: 'Let Thalia guide the rite',
        kind: SOLUTION_KIND.COMPANION_HELP,
        companionId: 'thalia',
        tier: 3,
        onSolve: {
          textKey: 'puzzle.solve.pool_thalia',
          rewards: { ap: 12 },
        },
      },
    ],
    onSolve: {
      worldFlags: { sacred_pool_awakened: true },
    },
  },
  {
    id: 'collapsed_feast_arch',
    regionId: 'ancient_temple',
    featureId: 'fallen_marble_arch',
    title: 'The Fallen Feast Arch',
    type: PUZZLE_TYPE.TRAVERSAL,
    tightSpace: true,
    stateFlag: 'puzzle_feast_arch_solved',
    examinedFlag: 'puzzle_feast_arch_examined',
    desc: 'A marble arch carved with feasting gods has collapsed, sealing the inner sanctum where rituals of growth still hum.',
    solutions: [
      {
        id: 'overwhelm_stone',
        label: 'Overwhelm the rubble with divine presence',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'overwhelm',
        dc: 14,
        onSolve: {
          textKey: 'puzzle.solve.arch_overwhelm',
          rewards: { xp: 35 },
        },
      },
      {
        id: 'pressure_crush',
        label: 'Crush stone with Pleasurable Pressure',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['pleasurable_pressure', 'form_of_abundance', 'true_overflow'],
        environmentTags: ['crush', 'swell'],
        onSolve: {
          textKey: 'puzzle.solve.arch_pressure',
          rewards: { xp: 45 },
        },
      },
      {
        id: 'greta_forge',
        label: 'Ask Greta to forge a breach',
        kind: SOLUTION_KIND.COMPANION_HELP,
        companionId: 'greta',
        tier: 2,
        onSolve: {
          textKey: 'puzzle.solve.arch_greta',
          rewards: { ap: 10 },
        },
      },
      {
        id: 'enormous_squeeze',
        label: 'Squeeze your enormous form through the gap',
        hint: 'Size has a price in tight halls — but immensity finds a way.',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 8,
        onSolve: {
          textKey: 'puzzle.solve.arch_squeeze',
          rewards: { xp: 50 },
        },
      },
      {
        id: 'sylvie_lore',
        label: 'Recite the arch\'s feasting inscription with Sylvie',
        kind: SOLUTION_KIND.COMPANION_HELP,
        companionId: 'sylvie',
        tier: 2,
        onSolve: {
          textKey: 'puzzle.solve.arch_sylvie',
          rewards: { xp: 40 },
        },
      },
      {
        id: 'fight_guardian_rubble',
        label: 'Battle the guardian haunting the rubble',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'temple_guardian',
        onSolve: {
          textKey: 'puzzle.solve.arch_combat',
          rewards: { xp: 50 },
        },
      },
    ],
    onSolve: {
      worldFlags: { feast_arch_cleared: true },
    },
  },

  // ─── Harvest's Hearth (dense village — 3 mysteries) ─────────────────────────

  {
    id: 'hearth_windmill_jam',
    regionId: 'harvest_hearth',
    featureId: 'hearth_windmill_wheel',
    title: 'The Jammed Windmill',
    type: PUZZLE_TYPE.ENVIRONMENTAL,
    stateFlag: 'puzzle_windmill_solved',
    examinedFlag: 'puzzle_windmill_examined',
    desc: 'The village windmill groans — its wheel seized with dough and greed. Fresh flour cannot flow until it turns again.',
    solutions: [
      {
        id: 'grace_unjam',
        label: 'Work the gears with graceful patience',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'grace',
        dc: 12,
        onSolve: { textKey: 'puzzle.solve.windmill_grace', rewards: { ap: 6, xp: 25 } },
      },
      {
        id: 'greta_help_mill',
        label: 'Ask Greta to hammer the wheel free',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'greta_smith',
        tier: 1,
        onSolve: { textKey: 'puzzle.solve.windmill_greta', rewards: { ap: 8 } },
      },
      {
        id: 'flavor_burst_feed',
        label: 'Bribe the mechanism with Flavor Burst',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['flavor_burst', 'rich_cream'],
        environmentTags: ['soften'],
        onSolve: { textKey: 'puzzle.solve.windmill_flavor', rewards: { xp: 30 } },
      },
      {
        id: 'fight_goblin_grease',
        label: 'Evict goblins squatting in the mill housing',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'gluttonous_goblin',
        onSolve: { textKey: 'puzzle.solve.windmill_combat', rewards: { xp: 35 } },
      },
    ],
    onSolve: { worldFlags: { windmill_turning: true } },
  },
  {
    id: 'hearth_shrine_bell',
    regionId: 'harvest_hearth',
    featureId: 'hearth_festival_shrine',
    title: 'The Festival Shrine Bell',
    type: PUZZLE_TYPE.RITUAL,
    stateFlag: 'puzzle_shrine_bell_solved',
    examinedFlag: 'puzzle_shrine_bell_examined',
    desc: 'A bronze bell hangs above the village shrine — too heavy to ring, yet the festival of abundance cannot begin without its peal.',
    solutions: [
      {
        id: 'overwhelm_bell',
        label: 'Ring it with overwhelming divine presence',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'overwhelm',
        dc: 13,
        onSolve: { textKey: 'puzzle.solve.shrine_overwhelm', rewards: { xp: 30 } },
      },
      {
        id: 'stage_pull',
        label: 'Pull the rope with plush, powerful mass',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 5,
        onSolve: { textKey: 'puzzle.solve.shrine_mass', rewards: { xp: 35 } },
      },
      {
        id: 'mira_ballad',
        label: 'Have Mira sing the bell awake',
        kind: SOLUTION_KIND.COMPANION_HELP,
        companionId: 'mira',
        tier: 2,
        onSolve: { textKey: 'puzzle.solve.shrine_mira', rewards: { ap: 10 } },
      },
      {
        id: 'perform_rite',
        label: 'Perform the ringing rite with theatrical flair',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'perform',
        dc: 11,
        onSolve: { textKey: 'puzzle.solve.shrine_perform', rewards: { xp: 25 } },
      },
    ],
    onSolve: { worldFlags: { hearth_festival_rung: true } },
  },

  // ─── Market Square (urban density — 2 mysteries) ────────────────────────────

  {
    id: 'market_spice_vault',
    regionId: 'market_square',
    featureId: 'market_spice_vault',
    title: 'The Locked Spice Vault',
    type: PUZZLE_TYPE.ENVIRONMENTAL,
    tightSpace: true,
    stateFlag: 'puzzle_spice_vault_solved',
    examinedFlag: 'puzzle_spice_vault_examined',
    desc: 'A merchant\'s underground vault reeks of saffron and secrets — rare spices that could flavor a feast for hundreds.',
    solutions: [
      {
        id: 'sneak_vault',
        label: 'Sneak through the crawlspace vents',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'sneak',
        dc: 14,
        onSolve: { textKey: 'puzzle.solve.vault_sneak', rewards: { xp: 30 } },
      },
      {
        id: 'seduce_merchant',
        label: 'Seduce the vault keeper into opening up',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'seduce',
        dc: 13,
        onSolve: { textKey: 'puzzle.solve.vault_seduce', rewards: { xp: 35 } },
      },
      {
        id: 'sylvie_key',
        label: 'Ask Sylvie about the vault\'s arcane lock',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'baker_sylvie',
        tier: 2,
        onSolve: { textKey: 'puzzle.solve.vault_sylvie', rewards: { ap: 10 } },
      },
      {
        id: 'rival_duel',
        label: 'Fight the rival guarding the vault entrance',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'rival_adventurer',
        onSolve: { textKey: 'puzzle.solve.vault_combat', rewards: { xp: 45 } },
      },
    ],
    onSolve: { worldFlags: { spice_vault_open: true }, ap: 12 },
  },

  // ─── Fertile Heartlands (wide rural — 2 mysteries) ───────────────────────────

  {
    id: 'dryad_thorn_hedge',
    regionId: 'fertile_heartlands',
    featureId: 'heartlands_thorn_hedge',
    title: 'The Dryad\'s Thorn Hedge',
    type: PUZZLE_TYPE.ENVIRONMENTAL,
    stateFlag: 'puzzle_thorn_hedge_solved',
    examinedFlag: 'puzzle_thorn_hedge_examined',
    desc: 'Living thorns weave a hedge across a hidden grove — beautiful, swollen with fruit, and fiercely territorial.',
    solutions: [
      {
        id: 'persuade_dryad',
        label: 'Persuade the hedge-spirit to part',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'persuade',
        dc: 13,
        onSolve: { textKey: 'puzzle.solve.hedge_persuade', rewards: { xp: 30 } },
      },
      {
        id: 'fertile_mist',
        label: 'Perfume the thorns with fertile mist',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['banquet_mist', 'feast_of_the_goddess', 'gorgaras_spark'],
        environmentTags: ['fertile', 'ritual'],
        onSolve: { textKey: 'puzzle.solve.hedge_mist', rewards: { xp: 35 } },
      },
      {
        id: 'lira_prayer',
        label: 'Pray with Lira for the hedge to yield',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'lira_priestess',
        tier: 1,
        onSolve: { textKey: 'puzzle.solve.hedge_lira', rewards: { ap: 8 } },
      },
      {
        id: 'fight_dryad',
        label: 'Battle the vinebound dryad guarding the grove',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'vinebound_dryad',
        onSolve: { textKey: 'puzzle.solve.hedge_combat', rewards: { xp: 50 } },
      },
    ],
    onSolve: { worldFlags: { dryad_grove_open: true } },
  },

  // ─── Shrine of the Thin Veil (intimate sacred — 2 mysteries) ───────────────────────

  {
    id: 'cradle_hunger_altar',
    regionId: 'gorgara_cradle',
    featureId: 'cradle_hunger_altar',
    title: 'Altar of First Hunger',
    type: PUZZLE_TYPE.RITUAL,
    stateFlag: 'puzzle_hunger_altar_solved',
    examinedFlag: 'puzzle_hunger_altar_examined',
    desc: 'A stone altar pulses with the goddess\'s first appetite — it demands a worthy offering before revealing its blessing.',
    solutions: [
      {
        id: 'indulge_offering',
        label: 'Offer indulgence at the altar',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'indulge',
        dc: 15,
        onSolve: { textKey: 'puzzle.solve.altar_indulge', rewards: { xp: 40 } },
      },
      {
        id: 'thalia_rite',
        label: 'Perform Thalia\'s hunger rite',
        kind: SOLUTION_KIND.COMPANION_HELP,
        companionId: 'thalia',
        tier: 2,
        onSolve: { textKey: 'puzzle.solve.altar_thalia', rewards: { ap: 15 } },
      },
      {
        id: 'abundance_120',
        label: 'Pour Feast Tide abundance into the altar',
        kind: SOLUTION_KIND.ABUNDANCE_MIN,
        points: 120,
        onSolve: { textKey: 'puzzle.solve.altar_abundance', rewards: { ap: 20, xp: 50 } },
      },
      {
        id: 'fight_inquisitor',
        label: 'Drive off the inquisitor desecrating the altar',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'purity_inquisitor',
        onSolve: { textKey: 'puzzle.solve.altar_combat', rewards: { xp: 55 } },
      },
    ],
    onSolve: { worldFlags: { hunger_altar_blessed: true } },
  },

  // ─── Ancient Temple (sprawling ruins — 3 mysteries) ─────────────────────────

  {
    id: 'temple_sealed_hall',
    regionId: 'ancient_temple',
    featureId: 'temple_sealed_feast_hall',
    title: 'The Sealed Feast Hall',
    type: PUZZLE_TYPE.ENVIRONMENTAL,
    tightSpace: true,
    stateFlag: 'puzzle_sealed_hall_solved',
    examinedFlag: 'puzzle_sealed_hall_examined',
    desc: 'Marble doors seal a hall where ancient feasts never ended — warmth and hunger leak through the cracks.',
    solutions: [
      {
        id: 'endure_seal',
        label: 'Endure the hall\'s hunger-pressure to force the doors',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'endure_growth',
        dc: 15,
        onSolve: { textKey: 'puzzle.solve.hall_endure', rewards: { xp: 40 } },
      },
      {
        id: 'divine_plump_door',
        label: 'Swollen divine magic on the sealed doors',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['divine_plump', 'form_of_abundance', 'matrons_blessing'],
        environmentTags: ['swell', 'ritual'],
        onSolve: { textKey: 'puzzle.solve.hall_divine', rewards: { xp: 45 } },
      },
      {
        id: 'squeeze_hall',
        label: 'Force your immensity through the narrow seam',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 9,
        ignoresTightSpace: true,
        onSolve: { textKey: 'puzzle.solve.hall_squeeze', rewards: { xp: 55 } },
      },
      {
        id: 'guardian_fight',
        label: 'Defeat the guardian sealing the hall',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'temple_guardian',
        onSolve: { textKey: 'puzzle.solve.hall_combat', rewards: { xp: 50 } },
      },
    ],
    onSolve: { worldFlags: { feast_hall_open: true } },
  },
  {
    id: 'temple_hunger_font',
    regionId: 'ancient_temple',
    featureId: 'temple_cursed_font',
    title: 'The Cursed Hunger Font',
    type: PUZZLE_TYPE.RITUAL,
    stateFlag: 'puzzle_hunger_font_solved',
    examinedFlag: 'puzzle_hunger_font_examined',
    desc: 'A fountain once blessed with feast-water now curdles with famine magic — only abundance can purify it.',
    solutions: [
      {
        id: 'feed_font',
        label: 'Feed the font with magical abundance',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['feast_of_the_goddess', 'lovers_feast', 'flavor_burst'],
        environmentTags: ['fertile', 'ritual'],
        onSolve: { textKey: 'puzzle.solve.font_feed', rewards: { xp: 40 } },
      },
      {
        id: 'sylvie_purify',
        label: 'Purify the inscription with Sylvie',
        kind: SOLUTION_KIND.COMPANION_HELP,
        companionId: 'sylvie',
        tier: 3,
        onSolve: { textKey: 'puzzle.solve.font_sylvie', rewards: { xp: 45 } },
      },
      {
        id: 'abundance_250',
        label: 'Overflow the font with Golden Overflow influence',
        kind: SOLUTION_KIND.ABUNDANCE_MIN,
        points: 250,
        onSolve: { textKey: 'puzzle.solve.font_abundance', rewards: { ap: 25, xp: 60 } },
      },
      {
        id: 'fight_hag',
        label: 'Confront the Famine Hag poisoning the font',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'famine_hag',
        onSolve: { textKey: 'puzzle.solve.font_combat', rewards: { xp: 70 } },
      },
    ],
    onSolve: { worldFlags: { hunger_font_purified: true } },
  },

  // ─── Task Group 3 — frontier & political creative obstacles ─────────────────

  {
    id: 'marches_blocked_pass',
    regionId: 'northern_marches',
    featureId: 'marches_landslide_pass',
    title: 'The Blocked Mountain Pass',
    type: PUZZLE_TYPE.TRAVERSAL,
    gateId: 'gate_marches_peak',
    stateFlag: 'puzzle_marches_pass_solved',
    examinedFlag: 'puzzle_marches_pass_examined',
    desc: 'Ice and pride seal the pass to Iron Peak — lean border soldiers sneer at travelers who smell of pastry.',
    unlocks: [
      { method: 'player_size_min', stage: 7 },
      { method: 'combat', enemyId: 'rival_adventurer' },
      { method: 'cast_spell', tags: ['crush'] },
    ],
    solutions: [
      {
        id: 'persuade_soldiers',
        label: 'Persuade the border captain with abundance gospel',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'persuade',
        dc: 14,
        onSolve: { textKey: 'puzzle.solve.marches_persuade', rewards: { xp: 35 } },
      },
      {
        id: 'greta_letter',
        label: 'Present Greta\'s forged letter of passage',
        kind: SOLUTION_KIND.NPC_RELATIONSHIP_MIN,
        npcId: 'greta_smith',
        tier: 2,
        onSolve: { textKey: 'puzzle.solve.marches_greta', rewards: { ap: 10 } },
      },
      {
        id: 'crush_ice',
        label: 'Shatter the ice with Pleasurable Pressure',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['pleasurable_pressure', 'form_of_abundance'],
        environmentTags: ['crush', 'swell'],
        onSolve: { textKey: 'puzzle.solve.marches_crush', rewards: { xp: 40 } },
      },
      {
        id: 'shoulder_pass',
        label: 'Shoulder through the landslide with divine mass',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 7,
        onSolve: { textKey: 'puzzle.solve.marches_shoulder', rewards: { xp: 45 } },
      },
      {
        id: 'duel_captain',
        label: 'Duel the rival captain blocking the pass',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'rival_adventurer',
        onSolve: { textKey: 'puzzle.solve.marches_combat', rewards: { xp: 50 } },
      },
    ],
    onSolve: { worldFlags: { marches_pass_open: true } },
  },
  {
    id: 'peak_forge_bridge',
    regionId: 'iron_peak_hold',
    featureId: 'peak_collapsed_bridge',
    title: 'The Collapsed Forge-Bridge',
    type: PUZZLE_TYPE.ENVIRONMENTAL,
    gateId: 'gate_peak_cradle',
    stateFlag: 'puzzle_peak_bridge_solved',
    examinedFlag: 'puzzle_peak_bridge_examined',
    desc: 'A dwarven forge-bridge lies rusted in the chasm — the sacred cradle waits beyond, if iron can be convinced to yield.',
    solutions: [
      {
        id: 'greta_forges',
        label: 'Ask Greta to forge a new span',
        kind: SOLUTION_KIND.FEED_NPC_STAGE,
        npcId: 'greta_smith',
        stage: 7,
        onSolve: { textKey: 'puzzle.solve.peak_greta', rewards: { ap: 15 } },
      },
      {
        id: 'ritual_rekindle',
        label: 'Rekindle the bridge-rite with fertile magic',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['banquet_mist', 'feast_of_the_goddess', 'gorgaras_spark'],
        environmentTags: ['ritual', 'fertile'],
        onSolve: { textKey: 'puzzle.solve.peak_ritual', rewards: { xp: 45 } },
      },
      {
        id: 'living_span',
        label: 'Span the chasm with your own immensity',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 8,
        onSolve: { textKey: 'puzzle.solve.peak_span', rewards: { xp: 55 } },
      },
      {
        id: 'overwhelm_rust',
        label: 'Overwhelm the rusted chains with divine presence',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'overwhelm',
        dc: 15,
        onSolve: { textKey: 'puzzle.solve.peak_overwhelm', rewards: { xp: 40 } },
      },
    ],
    onSolve: { worldFlags: { peak_bridge_open: true } },
  },
  {
    id: 'coast_velvet_seal',
    regionId: 'sapphire_coast',
    featureId: 'coast_velvet_gate',
    title: 'The Velvet Road Seal',
    type: PUZZLE_TYPE.SOCIAL,
    gateId: 'gate_coast_ember',
    stateFlag: 'puzzle_coast_seal_solved',
    examinedFlag: 'puzzle_coast_seal_examined',
    desc: 'Masked courtiers seal the coastal highway — charm, patronage, or transformed culture alone persuades them.',
    solutions: [
      {
        id: 'charm_seal',
        label: 'Charm the seal-guard with overflowing enchantment',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['overflowing_charm', 'jiggle_charm', 'feasts_whisper'],
        environmentTags: ['charm'],
        onSolve: { textKey: 'puzzle.solve.coast_charm', rewards: { xp: 35 } },
      },
      {
        id: 'vesperia_patron',
        label: 'Call upon Vesperia\'s noble patronage',
        kind: SOLUTION_KIND.FEED_NPC_STAGE,
        npcId: 'vesperia',
        stage: 6,
        onSolve: { textKey: 'puzzle.solve.coast_vesperia', rewards: { ap: 12 } },
      },
      {
        id: 'seduce_guard',
        label: 'Seduce the seal-master into opening the road',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'seduce',
        dc: 15,
        onSolve: { textKey: 'puzzle.solve.coast_seduce', rewards: { xp: 40 } },
      },
      {
        id: 'coast_blessed',
        label: 'Prove the Sapphire Coast has transformed',
        kind: SOLUTION_KIND.BLESS_REGION,
        regionId: 'sapphire_coast',
        transformationMin: 2,
        onSolve: { textKey: 'puzzle.solve.coast_blessed', rewards: { xp: 30 } },
      },
    ],
    onSolve: { worldFlags: { coast_road_open: true } },
  },
  {
    id: 'ember_starving_court',
    regionId: 'ember_duchy',
    featureId: 'ember_hungry_court',
    title: 'The Starving Ducal Court',
    type: PUZZLE_TYPE.SOCIAL,
    stateFlag: 'puzzle_ember_court_solved',
    examinedFlag: 'puzzle_ember_court_examined',
    desc: 'Ember\'s court starves behind velvet pride — they need a feast, not a sermon, before they will heed abundance.',
    solutions: [
      {
        id: 'hold_feast',
        label: 'Hold a communal court feast',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'perform',
        dc: 13,
        onSolve: { textKey: 'puzzle.solve.ember_feast', rewards: { xp: 40, ap: 15 } },
      },
      {
        id: 'banquet_rite',
        label: 'Perfume the hall with Banquet Mist',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['banquet_mist', 'feast_of_the_goddess', 'lovers_feast'],
        environmentTags: ['fertile', 'ritual'],
        onSolve: { textKey: 'puzzle.solve.ember_banquet', rewards: { xp: 45 } },
      },
      {
        id: 'abundance_court',
        label: 'Pour Golden Overflow influence into the court',
        kind: SOLUTION_KIND.ABUNDANCE_MIN,
        points: 150,
        onSolve: { textKey: 'puzzle.solve.ember_abundance', rewards: { ap: 20, xp: 50 } },
      },
      {
        id: 'feed_noble',
        label: 'Grow a court favorite until the hall applauds',
        kind: SOLUTION_KIND.FEED_NPC_STAGE,
        npcId: 'vesperia',
        stage: 7,
        onSolve: { textKey: 'puzzle.solve.ember_noble', rewards: { xp: 40 } },
      },
    ],
    onSolve: { worldFlags: { ember_court_fed: true, feast_held_ember_duchy: true } },
  },
  {
    id: 'ember_contested_approach',
    regionId: 'ember_duchy',
    featureId: 'ember_contested_gate',
    title: 'The Contested Citadel Road',
    type: PUZZLE_TYPE.SOCIAL,
    gateId: 'gate_ember_citadel',
    stateFlag: 'puzzle_ember_approach_solved',
    examinedFlag: 'puzzle_ember_approach_examined',
    desc: 'Purity zealots and newborn cults clash on the road to the Gilded Citadel — only overwhelming presence or politics clears the way.',
    unlocks: [
      { method: 'place_giant', minStage: 12, regionId: 'ember_duchy' },
      { method: 'communal_feast', regionId: 'ember_duchy' },
      { method: 'combat', enemyId: 'purity_inquisitor' },
    ],
    solutions: [
      {
        id: 'raise_landmark',
        label: 'Raise a beloved ally into a living landmark here',
        kind: SOLUTION_KIND.PLACE_GIANT,
        minStage: 12,
        onSolve: { textKey: 'puzzle.solve.ember_landmark', rewards: { xp: 80 } },
      },
      {
        id: 'duchy_blessed',
        label: 'Prove Ember Duchy is feast-blessed',
        kind: SOLUTION_KIND.BLESS_REGION,
        regionId: 'ember_duchy',
        transformationMin: 3,
        onSolve: { textKey: 'puzzle.solve.ember_transform', rewards: { xp: 50 } },
      },
      {
        id: 'break_inquisitor',
        label: 'Break the inquisitor blockade by force',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'purity_inquisitor',
        onSolve: { textKey: 'puzzle.solve.ember_combat', rewards: { xp: 60 } },
      },
      {
        id: 'persuade_factions',
        label: 'Persuade both factions to kneel to abundance',
        kind: SOLUTION_KIND.SKILL_CHECK,
        skillId: 'persuade',
        dc: 17,
        onSolve: { textKey: 'puzzle.solve.ember_persuade', rewards: { xp: 55 } },
      },
    ],
    onSolve: { worldFlags: { ember_road_clear: true } },
  },
  {
    id: 'citadel_purity_seal',
    regionId: 'gilded_citadel',
    featureId: 'citadel_purity_door',
    title: 'The Purity Grand Seal',
    type: PUZZLE_TYPE.RITUAL,
    stateFlag: 'puzzle_citadel_seal_solved',
    examinedFlag: 'puzzle_citadel_seal_examined',
    desc: 'The Gilded Citadel\'s grand seal rejects indulgence — only ritual, immensity, or a continent-swelling cult opens it.',
    solutions: [
      {
        id: 'mass_rite',
        label: 'Perform Mass Indulgence at the seal',
        kind: SOLUTION_KIND.SPELL,
        spellIds: ['mass_indulgence', 'gorgaras_awakening', 'feast_of_the_goddess'],
        environmentTags: ['ritual'],
        onSolve: { textKey: 'puzzle.solve.citadel_rite', rewards: { xp: 70 } },
      },
      {
        id: 'player_monolith',
        label: 'Become immobile grandeur before the seal',
        kind: SOLUTION_KIND.PLAYER_STAGE_MIN,
        stage: 11,
        onSolve: { textKey: 'puzzle.solve.citadel_monolith', rewards: { xp: 80 } },
      },
      {
        id: 'cult_landmark',
        label: 'Present a worshipped titan landmark as living proof',
        kind: SOLUTION_KIND.PLACE_GIANT,
        minStage: 12,
        onSolve: { textKey: 'puzzle.solve.citadel_cult', rewards: { xp: 90 } },
      },
      {
        id: 'fight_guardian',
        label: 'Shatter the seal-guardian in combat',
        kind: SOLUTION_KIND.COMBAT,
        enemyId: 'temple_guardian',
        onSolve: { textKey: 'puzzle.solve.citadel_combat', rewards: { xp: 75 } },
      },
    ],
    onSolve: { worldFlags: { citadel_seal_broken: true, faction_purity_weakened: true } },
  },
];
